// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: km_common/proto/algorithms.proto

package keymanager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Key Encapsulation Mechanism (KEM)
type KemAlgorithm int32

const (
	KemAlgorithm_KEM_ALGORITHM_UNSPECIFIED              KemAlgorithm = 0
	KemAlgorithm_KEM_ALGORITHM_DHKEM_X25519_HKDF_SHA256 KemAlgorithm = 1
)

// Enum value maps for KemAlgorithm.
var (
	KemAlgorithm_name = map[int32]string{
		0: "KEM_ALGORITHM_UNSPECIFIED",
		1: "KEM_ALGORITHM_DHKEM_X25519_HKDF_SHA256",
	}
	KemAlgorithm_value = map[string]int32{
		"KEM_ALGORITHM_UNSPECIFIED":              0,
		"KEM_ALGORITHM_DHKEM_X25519_HKDF_SHA256": 1,
	}
)

func (x KemAlgorithm) Enum() *KemAlgorithm {
	p := new(KemAlgorithm)
	*p = x
	return p
}

func (x KemAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KemAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_km_common_proto_algorithms_proto_enumTypes[0].Descriptor()
}

func (KemAlgorithm) Type() protoreflect.EnumType {
	return &file_km_common_proto_algorithms_proto_enumTypes[0]
}

func (x KemAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KemAlgorithm.Descriptor instead.
func (KemAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_km_common_proto_algorithms_proto_rawDescGZIP(), []int{0}
}

// Key Derivation Function (KDF)
type KdfAlgorithm int32

const (
	KdfAlgorithm_KDF_ALGORITHM_UNSPECIFIED KdfAlgorithm = 0
	KdfAlgorithm_KDF_ALGORITHM_HKDF_SHA256 KdfAlgorithm = 1
)

// Enum value maps for KdfAlgorithm.
var (
	KdfAlgorithm_name = map[int32]string{
		0: "KDF_ALGORITHM_UNSPECIFIED",
		1: "KDF_ALGORITHM_HKDF_SHA256",
	}
	KdfAlgorithm_value = map[string]int32{
		"KDF_ALGORITHM_UNSPECIFIED": 0,
		"KDF_ALGORITHM_HKDF_SHA256": 1,
	}
)

func (x KdfAlgorithm) Enum() *KdfAlgorithm {
	p := new(KdfAlgorithm)
	*p = x
	return p
}

func (x KdfAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KdfAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_km_common_proto_algorithms_proto_enumTypes[1].Descriptor()
}

func (KdfAlgorithm) Type() protoreflect.EnumType {
	return &file_km_common_proto_algorithms_proto_enumTypes[1]
}

func (x KdfAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KdfAlgorithm.Descriptor instead.
func (KdfAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_km_common_proto_algorithms_proto_rawDescGZIP(), []int{1}
}

// Authenticated Encryption with Associated Data (AEAD)
type AeadAlgorithm int32

const (
	AeadAlgorithm_AEAD_ALGORITHM_UNSPECIFIED AeadAlgorithm = 0
	AeadAlgorithm_AEAD_ALGORITHM_AES_256_GCM AeadAlgorithm = 1
)

// Enum value maps for AeadAlgorithm.
var (
	AeadAlgorithm_name = map[int32]string{
		0: "AEAD_ALGORITHM_UNSPECIFIED",
		1: "AEAD_ALGORITHM_AES_256_GCM",
	}
	AeadAlgorithm_value = map[string]int32{
		"AEAD_ALGORITHM_UNSPECIFIED": 0,
		"AEAD_ALGORITHM_AES_256_GCM": 1,
	}
)

func (x AeadAlgorithm) Enum() *AeadAlgorithm {
	p := new(AeadAlgorithm)
	*p = x
	return p
}

func (x AeadAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AeadAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_km_common_proto_algorithms_proto_enumTypes[2].Descriptor()
}

func (AeadAlgorithm) Type() protoreflect.EnumType {
	return &file_km_common_proto_algorithms_proto_enumTypes[2]
}

func (x AeadAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AeadAlgorithm.Descriptor instead.
func (AeadAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_km_common_proto_algorithms_proto_rawDescGZIP(), []int{2}
}

// Composite HPKE Algorithm suite
type HpkeAlgorithm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kem           KemAlgorithm           `protobuf:"varint,1,opt,name=kem,proto3,enum=keymanager.KemAlgorithm" json:"kem,omitempty"`
	Kdf           KdfAlgorithm           `protobuf:"varint,2,opt,name=kdf,proto3,enum=keymanager.KdfAlgorithm" json:"kdf,omitempty"`
	Aead          AeadAlgorithm          `protobuf:"varint,3,opt,name=aead,proto3,enum=keymanager.AeadAlgorithm" json:"aead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HpkeAlgorithm) Reset() {
	*x = HpkeAlgorithm{}
	mi := &file_km_common_proto_algorithms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HpkeAlgorithm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HpkeAlgorithm) ProtoMessage() {}

func (x *HpkeAlgorithm) ProtoReflect() protoreflect.Message {
	mi := &file_km_common_proto_algorithms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HpkeAlgorithm.ProtoReflect.Descriptor instead.
func (*HpkeAlgorithm) Descriptor() ([]byte, []int) {
	return file_km_common_proto_algorithms_proto_rawDescGZIP(), []int{0}
}

func (x *HpkeAlgorithm) GetKem() KemAlgorithm {
	if x != nil {
		return x.Kem
	}
	return KemAlgorithm_KEM_ALGORITHM_UNSPECIFIED
}

func (x *HpkeAlgorithm) GetKdf() KdfAlgorithm {
	if x != nil {
		return x.Kdf
	}
	return KdfAlgorithm_KDF_ALGORITHM_UNSPECIFIED
}

func (x *HpkeAlgorithm) GetAead() AeadAlgorithm {
	if x != nil {
		return x.Aead
	}
	return AeadAlgorithm_AEAD_ALGORITHM_UNSPECIFIED
}

// Specifies parameters for a particular algorithm type.
type AlgorithmParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Params:
	//
	//	*AlgorithmParams_KemId
	Params        isAlgorithmParams_Params `protobuf_oneof:"params"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlgorithmParams) Reset() {
	*x = AlgorithmParams{}
	mi := &file_km_common_proto_algorithms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlgorithmParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlgorithmParams) ProtoMessage() {}

func (x *AlgorithmParams) ProtoReflect() protoreflect.Message {
	mi := &file_km_common_proto_algorithms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlgorithmParams.ProtoReflect.Descriptor instead.
func (*AlgorithmParams) Descriptor() ([]byte, []int) {
	return file_km_common_proto_algorithms_proto_rawDescGZIP(), []int{1}
}

func (x *AlgorithmParams) GetParams() isAlgorithmParams_Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *AlgorithmParams) GetKemId() KemAlgorithm {
	if x != nil {
		if x, ok := x.Params.(*AlgorithmParams_KemId); ok {
			return x.KemId
		}
	}
	return KemAlgorithm_KEM_ALGORITHM_UNSPECIFIED
}

type isAlgorithmParams_Params interface {
	isAlgorithmParams_Params()
}

type AlgorithmParams_KemId struct {
	// KEM algorithm identifier (e.g., KEM_ALGORITHM_DHKEM_X25519_HKDF_SHA256).
	KemId KemAlgorithm `protobuf:"varint,1,opt,name=kem_id,json=kemId,proto3,enum=keymanager.KemAlgorithm,oneof"`
}

func (*AlgorithmParams_KemId) isAlgorithmParams_Params() {}

// Description of an algorithm.
type AlgorithmDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of algorithm, e.g., "kem".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Specific parameters associated with the algorithm type.
	Params        *AlgorithmParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlgorithmDetails) Reset() {
	*x = AlgorithmDetails{}
	mi := &file_km_common_proto_algorithms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlgorithmDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlgorithmDetails) ProtoMessage() {}

func (x *AlgorithmDetails) ProtoReflect() protoreflect.Message {
	mi := &file_km_common_proto_algorithms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlgorithmDetails.ProtoReflect.Descriptor instead.
func (*AlgorithmDetails) Descriptor() ([]byte, []int) {
	return file_km_common_proto_algorithms_proto_rawDescGZIP(), []int{2}
}

func (x *AlgorithmDetails) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AlgorithmDetails) GetParams() *AlgorithmParams {
	if x != nil {
		return x.Params
	}
	return nil
}

// Represents a cryptographic algorithm supported by the service.
type SupportedAlgorithm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// algorithm details.
	Algorithm     *AlgorithmDetails `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportedAlgorithm) Reset() {
	*x = SupportedAlgorithm{}
	mi := &file_km_common_proto_algorithms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportedAlgorithm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedAlgorithm) ProtoMessage() {}

func (x *SupportedAlgorithm) ProtoReflect() protoreflect.Message {
	mi := &file_km_common_proto_algorithms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedAlgorithm.ProtoReflect.Descriptor instead.
func (*SupportedAlgorithm) Descriptor() ([]byte, []int) {
	return file_km_common_proto_algorithms_proto_rawDescGZIP(), []int{3}
}

func (x *SupportedAlgorithm) GetAlgorithm() *AlgorithmDetails {
	if x != nil {
		return x.Algorithm
	}
	return nil
}

var File_km_common_proto_algorithms_proto protoreflect.FileDescriptor

const file_km_common_proto_algorithms_proto_rawDesc = "" +
	"\n" +
	" km_common/proto/algorithms.proto\x12\n" +
	"keymanager\"\x96\x01\n" +
	"\rHpkeAlgorithm\x12*\n" +
	"\x03kem\x18\x01 \x01(\x0e2\x18.keymanager.KemAlgorithmR\x03kem\x12*\n" +
	"\x03kdf\x18\x02 \x01(\x0e2\x18.keymanager.KdfAlgorithmR\x03kdf\x12-\n" +
	"\x04aead\x18\x03 \x01(\x0e2\x19.keymanager.AeadAlgorithmR\x04aead\"N\n" +
	"\x0fAlgorithmParams\x121\n" +
	"\x06kem_id\x18\x01 \x01(\x0e2\x18.keymanager.KemAlgorithmH\x00R\x05kemIdB\b\n" +
	"\x06params\"[\n" +
	"\x10AlgorithmDetails\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x123\n" +
	"\x06params\x18\x02 \x01(\v2\x1b.keymanager.AlgorithmParamsR\x06params\"P\n" +
	"\x12SupportedAlgorithm\x12:\n" +
	"\talgorithm\x18\x01 \x01(\v2\x1c.keymanager.AlgorithmDetailsR\talgorithm*Y\n" +
	"\fKemAlgorithm\x12\x1d\n" +
	"\x19KEM_ALGORITHM_UNSPECIFIED\x10\x00\x12*\n" +
	"&KEM_ALGORITHM_DHKEM_X25519_HKDF_SHA256\x10\x01*L\n" +
	"\fKdfAlgorithm\x12\x1d\n" +
	"\x19KDF_ALGORITHM_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19KDF_ALGORITHM_HKDF_SHA256\x10\x01*O\n" +
	"\rAeadAlgorithm\x12\x1e\n" +
	"\x1aAEAD_ALGORITHM_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aAEAD_ALGORITHM_AES_256_GCM\x10\x01BFZDgithub.com/google/go-tpm-tools/keymanager/km_common/proto;keymanagerb\x06proto3"

var (
	file_km_common_proto_algorithms_proto_rawDescOnce sync.Once
	file_km_common_proto_algorithms_proto_rawDescData []byte
)

func file_km_common_proto_algorithms_proto_rawDescGZIP() []byte {
	file_km_common_proto_algorithms_proto_rawDescOnce.Do(func() {
		file_km_common_proto_algorithms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_km_common_proto_algorithms_proto_rawDesc), len(file_km_common_proto_algorithms_proto_rawDesc)))
	})
	return file_km_common_proto_algorithms_proto_rawDescData
}

var file_km_common_proto_algorithms_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_km_common_proto_algorithms_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_km_common_proto_algorithms_proto_goTypes = []any{
	(KemAlgorithm)(0),          // 0: keymanager.KemAlgorithm
	(KdfAlgorithm)(0),          // 1: keymanager.KdfAlgorithm
	(AeadAlgorithm)(0),         // 2: keymanager.AeadAlgorithm
	(*HpkeAlgorithm)(nil),      // 3: keymanager.HpkeAlgorithm
	(*AlgorithmParams)(nil),    // 4: keymanager.AlgorithmParams
	(*AlgorithmDetails)(nil),   // 5: keymanager.AlgorithmDetails
	(*SupportedAlgorithm)(nil), // 6: keymanager.SupportedAlgorithm
}
var file_km_common_proto_algorithms_proto_depIdxs = []int32{
	0, // 0: keymanager.HpkeAlgorithm.kem:type_name -> keymanager.KemAlgorithm
	1, // 1: keymanager.HpkeAlgorithm.kdf:type_name -> keymanager.KdfAlgorithm
	2, // 2: keymanager.HpkeAlgorithm.aead:type_name -> keymanager.AeadAlgorithm
	0, // 3: keymanager.AlgorithmParams.kem_id:type_name -> keymanager.KemAlgorithm
	4, // 4: keymanager.AlgorithmDetails.params:type_name -> keymanager.AlgorithmParams
	5, // 5: keymanager.SupportedAlgorithm.algorithm:type_name -> keymanager.AlgorithmDetails
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_km_common_proto_algorithms_proto_init() }
func file_km_common_proto_algorithms_proto_init() {
	if File_km_common_proto_algorithms_proto != nil {
		return
	}
	file_km_common_proto_algorithms_proto_msgTypes[1].OneofWrappers = []any{
		(*AlgorithmParams_KemId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_km_common_proto_algorithms_proto_rawDesc), len(file_km_common_proto_algorithms_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_km_common_proto_algorithms_proto_goTypes,
		DependencyIndexes: file_km_common_proto_algorithms_proto_depIdxs,
		EnumInfos:         file_km_common_proto_algorithms_proto_enumTypes,
		MessageInfos:      file_km_common_proto_algorithms_proto_msgTypes,
	}.Build()
	File_km_common_proto_algorithms_proto = out.File
	file_km_common_proto_algorithms_proto_goTypes = nil
	file_km_common_proto_algorithms_proto_depIdxs = nil
}
