// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: keymanager/km_common/proto/errors.proto

package keymanager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error int32

const (
	Error_ERROR_SUCCESS               Error = 0
	Error_ERROR_INTERNAL              Error = 1
	Error_ERROR_INVALID_ARGUMENT      Error = 2
	Error_ERROR_NOT_FOUND             Error = 3
	Error_ERROR_ALREADY_EXISTS        Error = 4
	Error_ERROR_PERMISSION_DENIED     Error = 5
	Error_ERROR_UNAUTHENTICATED       Error = 6
	Error_ERROR_UNSUPPORTED_ALGORITHM Error = 7
	Error_ERROR_INVALID_KEY           Error = 8
	Error_ERROR_CRYPTO_ERROR          Error = 9
	Error_ERROR_DECRYPTION_FAILURE    Error = 10
	Error_ERROR_ENCRYPTION_FAILURE    Error = 11
	Error_ERROR_DECAPSULATION_FAILURE Error = 12
)

// Enum value maps for Error.
var (
	Error_name = map[int32]string{
		0:  "ERROR_SUCCESS",
		1:  "ERROR_INTERNAL",
		2:  "ERROR_INVALID_ARGUMENT",
		3:  "ERROR_NOT_FOUND",
		4:  "ERROR_ALREADY_EXISTS",
		5:  "ERROR_PERMISSION_DENIED",
		6:  "ERROR_UNAUTHENTICATED",
		7:  "ERROR_UNSUPPORTED_ALGORITHM",
		8:  "ERROR_INVALID_KEY",
		9:  "ERROR_CRYPTO_ERROR",
		10: "ERROR_DECRYPTION_FAILURE",
		11: "ERROR_ENCRYPTION_FAILURE",
		12: "ERROR_DECAPSULATION_FAILURE",
	}
	Error_value = map[string]int32{
		"ERROR_SUCCESS":               0,
		"ERROR_INTERNAL":              1,
		"ERROR_INVALID_ARGUMENT":      2,
		"ERROR_NOT_FOUND":             3,
		"ERROR_ALREADY_EXISTS":        4,
		"ERROR_PERMISSION_DENIED":     5,
		"ERROR_UNAUTHENTICATED":       6,
		"ERROR_UNSUPPORTED_ALGORITHM": 7,
		"ERROR_INVALID_KEY":           8,
		"ERROR_CRYPTO_ERROR":          9,
		"ERROR_DECRYPTION_FAILURE":    10,
		"ERROR_ENCRYPTION_FAILURE":    11,
		"ERROR_DECAPSULATION_FAILURE": 12,
	}
)

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}

func (x Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error) Descriptor() protoreflect.EnumDescriptor {
	return file_keymanager_km_common_proto_errors_proto_enumTypes[0].Descriptor()
}

func (Error) Type() protoreflect.EnumType {
	return &file_keymanager_km_common_proto_errors_proto_enumTypes[0]
}

func (x Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error.Descriptor instead.
func (Error) EnumDescriptor() ([]byte, []int) {
	return file_keymanager_km_common_proto_errors_proto_rawDescGZIP(), []int{0}
}

var File_keymanager_km_common_proto_errors_proto protoreflect.FileDescriptor

const file_keymanager_km_common_proto_errors_proto_rawDesc = "" +
	"\n" +
	"'keymanager/km_common/proto/errors.proto\x12\n" +
	"keymanager*\xde\x02\n" +
	"\x05Error\x12\x11\n" +
	"\rERROR_SUCCESS\x10\x00\x12\x12\n" +
	"\x0eERROR_INTERNAL\x10\x01\x12\x1a\n" +
	"\x16ERROR_INVALID_ARGUMENT\x10\x02\x12\x13\n" +
	"\x0fERROR_NOT_FOUND\x10\x03\x12\x18\n" +
	"\x14ERROR_ALREADY_EXISTS\x10\x04\x12\x1b\n" +
	"\x17ERROR_PERMISSION_DENIED\x10\x05\x12\x19\n" +
	"\x15ERROR_UNAUTHENTICATED\x10\x06\x12\x1f\n" +
	"\x1bERROR_UNSUPPORTED_ALGORITHM\x10\a\x12\x15\n" +
	"\x11ERROR_INVALID_KEY\x10\b\x12\x16\n" +
	"\x12ERROR_CRYPTO_ERROR\x10\t\x12\x1c\n" +
	"\x18ERROR_DECRYPTION_FAILURE\x10\n" +
	"\x12\x1c\n" +
	"\x18ERROR_ENCRYPTION_FAILURE\x10\v\x12\x1f\n" +
	"\x1bERROR_DECAPSULATION_FAILURE\x10\fBFZDgithub.com/google/go-tpm-tools/keymanager/km_common/proto;keymanagerb\x06proto3"

var (
	file_keymanager_km_common_proto_errors_proto_rawDescOnce sync.Once
	file_keymanager_km_common_proto_errors_proto_rawDescData []byte
)

func file_keymanager_km_common_proto_errors_proto_rawDescGZIP() []byte {
	file_keymanager_km_common_proto_errors_proto_rawDescOnce.Do(func() {
		file_keymanager_km_common_proto_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keymanager_km_common_proto_errors_proto_rawDesc), len(file_keymanager_km_common_proto_errors_proto_rawDesc)))
	})
	return file_keymanager_km_common_proto_errors_proto_rawDescData
}

var file_keymanager_km_common_proto_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_keymanager_km_common_proto_errors_proto_goTypes = []any{
	(Error)(0), // 0: keymanager.Error
}
var file_keymanager_km_common_proto_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_keymanager_km_common_proto_errors_proto_init() }
func file_keymanager_km_common_proto_errors_proto_init() {
	if File_keymanager_km_common_proto_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keymanager_km_common_proto_errors_proto_rawDesc), len(file_keymanager_km_common_proto_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keymanager_km_common_proto_errors_proto_goTypes,
		DependencyIndexes: file_keymanager_km_common_proto_errors_proto_depIdxs,
		EnumInfos:         file_keymanager_km_common_proto_errors_proto_enumTypes,
	}.Build()
	File_keymanager_km_common_proto_errors_proto = out.File
	file_keymanager_km_common_proto_errors_proto_goTypes = nil
	file_keymanager_km_common_proto_errors_proto_depIdxs = nil
}
