// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: keymanager/km_common/proto/payload.proto

package keymanager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The results of an Encaps operation.
type KemCiphertext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     KemAlgorithm           `protobuf:"varint,1,opt,name=algorithm,proto3,enum=keymanager.KemAlgorithm" json:"algorithm,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"` // `Nenc` bytes long.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KemCiphertext) Reset() {
	*x = KemCiphertext{}
	mi := &file_keymanager_km_common_proto_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KemCiphertext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KemCiphertext) ProtoMessage() {}

func (x *KemCiphertext) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_km_common_proto_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KemCiphertext.ProtoReflect.Descriptor instead.
func (*KemCiphertext) Descriptor() ([]byte, []int) {
	return file_keymanager_km_common_proto_payload_proto_rawDescGZIP(), []int{0}
}

func (x *KemCiphertext) GetAlgorithm() KemAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return KemAlgorithm_KEM_ALGORITHM_UNSPECIFIED
}

func (x *KemCiphertext) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

// The results of a Decaps operation.
type KemSharedSecret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     KemAlgorithm           `protobuf:"varint,1,opt,name=algorithm,proto3,enum=keymanager.KemAlgorithm" json:"algorithm,omitempty"`
	Secret        []byte                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"` // `Nsecret` bytes long.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KemSharedSecret) Reset() {
	*x = KemSharedSecret{}
	mi := &file_keymanager_km_common_proto_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KemSharedSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KemSharedSecret) ProtoMessage() {}

func (x *KemSharedSecret) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_km_common_proto_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KemSharedSecret.ProtoReflect.Descriptor instead.
func (*KemSharedSecret) Descriptor() ([]byte, []int) {
	return file_keymanager_km_common_proto_payload_proto_rawDescGZIP(), []int{1}
}

func (x *KemSharedSecret) GetAlgorithm() KemAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return KemAlgorithm_KEM_ALGORITHM_UNSPECIFIED
}

func (x *KemSharedSecret) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

type HpkePayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Algorithm         *HpkeAlgorithm         `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	KemCiphertext     []byte                 `protobuf:"bytes,2,opt,name=kem_ciphertext,json=kemCiphertext,proto3" json:"kem_ciphertext,omitempty"`             // `Nenc` bytes long.
	PayloadCiphertext []byte                 `protobuf:"bytes,3,opt,name=payload_ciphertext,json=payloadCiphertext,proto3" json:"payload_ciphertext,omitempty"` // Encrypted data.
	AuthenticationTag []byte                 `protobuf:"bytes,4,opt,name=authentication_tag,json=authenticationTag,proto3" json:"authentication_tag,omitempty"` // `Nt` bytes long.
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HpkePayload) Reset() {
	*x = HpkePayload{}
	mi := &file_keymanager_km_common_proto_payload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HpkePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HpkePayload) ProtoMessage() {}

func (x *HpkePayload) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_km_common_proto_payload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HpkePayload.ProtoReflect.Descriptor instead.
func (*HpkePayload) Descriptor() ([]byte, []int) {
	return file_keymanager_km_common_proto_payload_proto_rawDescGZIP(), []int{2}
}

func (x *HpkePayload) GetAlgorithm() *HpkeAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return nil
}

func (x *HpkePayload) GetKemCiphertext() []byte {
	if x != nil {
		return x.KemCiphertext
	}
	return nil
}

func (x *HpkePayload) GetPayloadCiphertext() []byte {
	if x != nil {
		return x.PayloadCiphertext
	}
	return nil
}

func (x *HpkePayload) GetAuthenticationTag() []byte {
	if x != nil {
		return x.AuthenticationTag
	}
	return nil
}

var File_keymanager_km_common_proto_payload_proto protoreflect.FileDescriptor

const file_keymanager_km_common_proto_payload_proto_rawDesc = "" +
	"\n" +
	"(keymanager/km_common/proto/payload.proto\x12\n" +
	"keymanager\x1a+keymanager/km_common/proto/algorithms.proto\"g\n" +
	"\rKemCiphertext\x126\n" +
	"\talgorithm\x18\x01 \x01(\x0e2\x18.keymanager.KemAlgorithmR\talgorithm\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fR\n" +
	"ciphertext\"a\n" +
	"\x0fKemSharedSecret\x126\n" +
	"\talgorithm\x18\x01 \x01(\x0e2\x18.keymanager.KemAlgorithmR\talgorithm\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\fR\x06secret\"\xcb\x01\n" +
	"\vHpkePayload\x127\n" +
	"\talgorithm\x18\x01 \x01(\v2\x19.keymanager.HpkeAlgorithmR\talgorithm\x12%\n" +
	"\x0ekem_ciphertext\x18\x02 \x01(\fR\rkemCiphertext\x12-\n" +
	"\x12payload_ciphertext\x18\x03 \x01(\fR\x11payloadCiphertext\x12-\n" +
	"\x12authentication_tag\x18\x04 \x01(\fR\x11authenticationTagBFZDgithub.com/google/go-tpm-tools/keymanager/km_common/proto;keymanagerb\x06proto3"

var (
	file_keymanager_km_common_proto_payload_proto_rawDescOnce sync.Once
	file_keymanager_km_common_proto_payload_proto_rawDescData []byte
)

func file_keymanager_km_common_proto_payload_proto_rawDescGZIP() []byte {
	file_keymanager_km_common_proto_payload_proto_rawDescOnce.Do(func() {
		file_keymanager_km_common_proto_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keymanager_km_common_proto_payload_proto_rawDesc), len(file_keymanager_km_common_proto_payload_proto_rawDesc)))
	})
	return file_keymanager_km_common_proto_payload_proto_rawDescData
}

var file_keymanager_km_common_proto_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_keymanager_km_common_proto_payload_proto_goTypes = []any{
	(*KemCiphertext)(nil),   // 0: keymanager.KemCiphertext
	(*KemSharedSecret)(nil), // 1: keymanager.KemSharedSecret
	(*HpkePayload)(nil),     // 2: keymanager.HpkePayload
	(KemAlgorithm)(0),       // 3: keymanager.KemAlgorithm
	(*HpkeAlgorithm)(nil),   // 4: keymanager.HpkeAlgorithm
}
var file_keymanager_km_common_proto_payload_proto_depIdxs = []int32{
	3, // 0: keymanager.KemCiphertext.algorithm:type_name -> keymanager.KemAlgorithm
	3, // 1: keymanager.KemSharedSecret.algorithm:type_name -> keymanager.KemAlgorithm
	4, // 2: keymanager.HpkePayload.algorithm:type_name -> keymanager.HpkeAlgorithm
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_keymanager_km_common_proto_payload_proto_init() }
func file_keymanager_km_common_proto_payload_proto_init() {
	if File_keymanager_km_common_proto_payload_proto != nil {
		return
	}
	file_keymanager_km_common_proto_algorithms_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keymanager_km_common_proto_payload_proto_rawDesc), len(file_keymanager_km_common_proto_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keymanager_km_common_proto_payload_proto_goTypes,
		DependencyIndexes: file_keymanager_km_common_proto_payload_proto_depIdxs,
		MessageInfos:      file_keymanager_km_common_proto_payload_proto_msgTypes,
	}.Build()
	File_keymanager_km_common_proto_payload_proto = out.File
	file_keymanager_km_common_proto_payload_proto_goTypes = nil
	file_keymanager_km_common_proto_payload_proto_depIdxs = nil
}
