#ifndef KM_COMMON_FFI_H_
#define KM_COMMON_FFI_H_

/* Auto-generated by cbindgen. DO NOT EDIT. */

#include <stdint.h>

#define MAX_ALGORITHM_LEN 128

#define MAX_PUBLIC_KEY_LEN 2048

enum Status
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  Status_Success = 0,
  Status_InternalError = 1,
  Status_InvalidArgument = 2,
  Status_NotFound = 3,
  Status_AlreadyExists = 4,
  Status_PermissionDenied = 5,
  Status_Unauthenticated = 6,
  Status_UnsupportedAlgorithm = 7,
  Status_InvalidKey = 8,
  Status_CryptoError = 9,
  Status_DecryptionFailure = 10,
  Status_EncryptionFailure = 11,
  Status_DecapsulationFailure = 12,
};
#ifndef __cplusplus
typedef int32_t Status;
#endif // __cplusplus

#endif  /* KM_COMMON_FFI_H_ */
