#ifndef KM_COMMON_FFI_H_
#define KM_COMMON_FFI_H_

/* Auto-generated by cbindgen. DO NOT EDIT. */

#include <stdint.h>

#define MAX_ALGORITHM_LEN 128

#define MAX_PUBLIC_KEY_LEN 2048

enum Error
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  Error_Success = 0,
  Error_Internal = 1,
  Error_InvalidArgument = 2,
  Error_NotFound = 3,
  Error_AlreadyExists = 4,
  Error_PermissionDenied = 5,
  Error_Unauthenticated = 6,
  Error_UnsupportedAlgorithm = 7,
  Error_InvalidKey = 8,
  Error_CryptoError = 9,
  Error_DecryptionFailure = 10,
  Error_EncryptionFailure = 11,
  Error_DecapsulationFailure = 12,
};
#ifndef __cplusplus
typedef int32_t Error;
#endif // __cplusplus

#endif  /* KM_COMMON_FFI_H_ */
