// Code generated by script. DO NOT EDIT.

//go:build require
// +build require

// Package require blank-imports all lower-level C dependency packages.
// This package is intended to be imported *only* by main packages or tests
// that need these C dependencies linked.
// See Google's Go Style Decisions on blank imports:
// http://go/go-style/decisions#import-blank
package simulator

import (
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/Samples/google"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/include"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/include/ltc"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/include/ossl"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/include/prototypes"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/include/wolf"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/asymmetric"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/attachedcomponent"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/attestation"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/capability"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/clocktimer"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/commandaudit"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/context"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/da"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/duplication"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/ea"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/ecdaa"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/fieldupgrade"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/hashhmac"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/hierarchy"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/misc"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/nvstorage"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/object"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/pcr"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/random"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/session"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/signature"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/startup"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/symmetric"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/testing"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/command/vendor"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/crypt"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/crypt/ltc"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/crypt/ossl"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/crypt/wolf"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/events"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/main"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/subsystem"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/support"
	_ "github.com/google/go-tpm-tools/simulator/ms-tpm-20-ref/TPMCmd/tpm/src/x509"
)
