container:
  image: golang:latest

env:
  GOPROXY: https://proxy.golang.org
  GO111MODULE: on

test_task:
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  submodule_cache:
    fingerprint_script: cat .gitmodules
    folder: simulator/internal/ms-tpm-20-ref
  get_script: git submodule update --init --depth=1
  build_script: go build -v ./...
  test_script: go test -v ./...
