container:
  dockerfile: Dockerfile

env:
  GOPROXY: https://proxy.golang.org
  GO111MODULE: on

test_task:
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  submodule_script: git submodule update --init --depth=1
  build_script: go build -v ./...
  test_script: go test -v ./...
