// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: hostservice.proto

package hostservicepb

import (
	attestation "github.com/GoogleCloudPlatform/confidential-space/server/proto/gen/attestation"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHostAttestationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     []byte                 `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostAttestationRequest) Reset() {
	*x = GetHostAttestationRequest{}
	mi := &file_hostservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostAttestationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostAttestationRequest) ProtoMessage() {}

func (x *GetHostAttestationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostAttestationRequest.ProtoReflect.Descriptor instead.
func (*GetHostAttestationRequest) Descriptor() ([]byte, []int) {
	return file_hostservice_proto_rawDescGZIP(), []int{0}
}

func (x *GetHostAttestationRequest) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

type GetHostAttestationResponse struct {
	state           protoimpl.MessageState       `protogen:"open.v1"`
	HostAttestation *attestation.HostAttestation `protobuf:"bytes,1,opt,name=host_attestation,json=hostAttestation,proto3" json:"host_attestation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetHostAttestationResponse) Reset() {
	*x = GetHostAttestationResponse{}
	mi := &file_hostservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostAttestationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostAttestationResponse) ProtoMessage() {}

func (x *GetHostAttestationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostAttestationResponse.ProtoReflect.Descriptor instead.
func (*GetHostAttestationResponse) Descriptor() ([]byte, []int) {
	return file_hostservice_proto_rawDescGZIP(), []int{1}
}

func (x *GetHostAttestationResponse) GetHostAttestation() *attestation.HostAttestation {
	if x != nil {
		return x.HostAttestation
	}
	return nil
}

type SelfTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfTestRequest) Reset() {
	*x = SelfTestRequest{}
	mi := &file_hostservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfTestRequest) ProtoMessage() {}

func (x *SelfTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfTestRequest.ProtoReflect.Descriptor instead.
func (*SelfTestRequest) Descriptor() ([]byte, []int) {
	return file_hostservice_proto_rawDescGZIP(), []int{2}
}

type SelfTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfTestResponse) Reset() {
	*x = SelfTestResponse{}
	mi := &file_hostservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfTestResponse) ProtoMessage() {}

func (x *SelfTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfTestResponse.ProtoReflect.Descriptor instead.
func (*SelfTestResponse) Descriptor() ([]byte, []int) {
	return file_hostservice_proto_rawDescGZIP(), []int{3}
}

func (x *SelfTestResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_hostservice_proto protoreflect.FileDescriptor

const file_hostservice_proto_rawDesc = "" +
	"\n" +
	"\x11hostservice.proto\x12\vhostservice\x1a\x11attestation.proto\"9\n" +
	"\x19GetHostAttestationRequest\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\fR\tchallenge\"l\n" +
	"\x1aGetHostAttestationResponse\x12N\n" +
	"\x10host_attestation\x18\x01 \x01(\v2#.confidential_space.HostAttestationR\x0fhostAttestation\"\x11\n" +
	"\x0fSelfTestRequest\".\n" +
	"\x10SelfTestResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse2\xbd\x01\n" +
	"\vHostService\x12G\n" +
	"\bSelfTest\x12\x1c.hostservice.SelfTestRequest\x1a\x1d.hostservice.SelfTestResponse\x12e\n" +
	"\x12GetHostAttestation\x12&.hostservice.GetHostAttestationRequest\x1a'.hostservice.GetHostAttestationResponseB:Z8github.com/google/go-tpm-tools/agent/proto/hostservicepbb\x06proto3"

var (
	file_hostservice_proto_rawDescOnce sync.Once
	file_hostservice_proto_rawDescData []byte
)

func file_hostservice_proto_rawDescGZIP() []byte {
	file_hostservice_proto_rawDescOnce.Do(func() {
		file_hostservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hostservice_proto_rawDesc), len(file_hostservice_proto_rawDesc)))
	})
	return file_hostservice_proto_rawDescData
}

var file_hostservice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hostservice_proto_goTypes = []any{
	(*GetHostAttestationRequest)(nil),   // 0: hostservice.GetHostAttestationRequest
	(*GetHostAttestationResponse)(nil),  // 1: hostservice.GetHostAttestationResponse
	(*SelfTestRequest)(nil),             // 2: hostservice.SelfTestRequest
	(*SelfTestResponse)(nil),            // 3: hostservice.SelfTestResponse
	(*attestation.HostAttestation)(nil), // 4: confidential_space.HostAttestation
}
var file_hostservice_proto_depIdxs = []int32{
	4, // 0: hostservice.GetHostAttestationResponse.host_attestation:type_name -> confidential_space.HostAttestation
	2, // 1: hostservice.HostService.SelfTest:input_type -> hostservice.SelfTestRequest
	0, // 2: hostservice.HostService.GetHostAttestation:input_type -> hostservice.GetHostAttestationRequest
	3, // 3: hostservice.HostService.SelfTest:output_type -> hostservice.SelfTestResponse
	1, // 4: hostservice.HostService.GetHostAttestation:output_type -> hostservice.GetHostAttestationResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hostservice_proto_init() }
func file_hostservice_proto_init() {
	if File_hostservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hostservice_proto_rawDesc), len(file_hostservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hostservice_proto_goTypes,
		DependencyIndexes: file_hostservice_proto_depIdxs,
		MessageInfos:      file_hostservice_proto_msgTypes,
	}.Build()
	File_hostservice_proto = out.File
	file_hostservice_proto_goTypes = nil
	file_hostservice_proto_depIdxs = nil
}
