// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: keymanager/key_protection_service/proto/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_keymanager_key_protection_service_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_key_protection_service_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_keymanager_key_protection_service_proto_api_proto_rawDescGZIP(), []int{0}
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KpsBootToken  string                 `protobuf:"bytes,1,opt,name=kps_boot_token,json=kpsBootToken,proto3" json:"kps_boot_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_keymanager_key_protection_service_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_key_protection_service_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_keymanager_key_protection_service_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetKpsBootToken() string {
	if x != nil {
		return x.KpsBootToken
	}
	return ""
}

var File_keymanager_key_protection_service_proto_api_proto protoreflect.FileDescriptor

const file_keymanager_key_protection_service_proto_api_proto_rawDesc = "" +
	"\n" +
	"1keymanager/key_protection_service/proto/api.proto\x12!keymanager.key_protection_service\"\x12\n" +
	"\x10HeartbeatRequest\"9\n" +
	"\x11HeartbeatResponse\x12$\n" +
	"\x0ekps_boot_token\x18\x01 \x01(\tR\fkpsBootToken2\x8e\x01\n" +
	"\x14KeyProtectionService\x12v\n" +
	"\tHeartbeat\x123.keymanager.key_protection_service.HeartbeatRequest\x1a4.keymanager.key_protection_service.HeartbeatResponseBLZJgithub.com/google/go-tpm-tools/keymanager/key_protection_service/proto;apib\x06proto3"

var (
	file_keymanager_key_protection_service_proto_api_proto_rawDescOnce sync.Once
	file_keymanager_key_protection_service_proto_api_proto_rawDescData []byte
)

func file_keymanager_key_protection_service_proto_api_proto_rawDescGZIP() []byte {
	file_keymanager_key_protection_service_proto_api_proto_rawDescOnce.Do(func() {
		file_keymanager_key_protection_service_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keymanager_key_protection_service_proto_api_proto_rawDesc), len(file_keymanager_key_protection_service_proto_api_proto_rawDesc)))
	})
	return file_keymanager_key_protection_service_proto_api_proto_rawDescData
}

var file_keymanager_key_protection_service_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_keymanager_key_protection_service_proto_api_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),  // 0: keymanager.key_protection_service.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 1: keymanager.key_protection_service.HeartbeatResponse
}
var file_keymanager_key_protection_service_proto_api_proto_depIdxs = []int32{
	0, // 0: keymanager.key_protection_service.KeyProtectionService.Heartbeat:input_type -> keymanager.key_protection_service.HeartbeatRequest
	1, // 1: keymanager.key_protection_service.KeyProtectionService.Heartbeat:output_type -> keymanager.key_protection_service.HeartbeatResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_keymanager_key_protection_service_proto_api_proto_init() }
func file_keymanager_key_protection_service_proto_api_proto_init() {
	if File_keymanager_key_protection_service_proto_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keymanager_key_protection_service_proto_api_proto_rawDesc), len(file_keymanager_key_protection_service_proto_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keymanager_key_protection_service_proto_api_proto_goTypes,
		DependencyIndexes: file_keymanager_key_protection_service_proto_api_proto_depIdxs,
		MessageInfos:      file_keymanager_key_protection_service_proto_api_proto_msgTypes,
	}.Build()
	File_keymanager_key_protection_service_proto_api_proto = out.File
	file_keymanager_key_protection_service_proto_api_proto_goTypes = nil
	file_keymanager_key_protection_service_proto_api_proto_depIdxs = nil
}
