# From the current directory:
# gcloud builds submit --tag us-west1-docker.pkg.dev/confidential-space-images-dev/cs-integ-test-images/nginx-unprivileged:latest
FROM docker.io/nginxinc/nginx-unprivileged:latest
LABEL "tee.launch_policy.allow_cmd_override"="true"
