#ifndef KPS_KEY_CUSTODY_CORE_H_
#define KPS_KEY_CUSTODY_CORE_H_

/* Auto-generated by cbindgen. DO NOT EDIT. */

#include <stddef.h>
#include <stdint.h>
#include "../../../km_common/include/km_algorithms.h"

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

int32_t key_manager_generate_kem_keypair(KmHpkeAlgorithm algo,
                                         const uint8_t *binding_pubkey,
                                         size_t binding_pubkey_len,
                                         uint64_t expiry_secs,
                                         uint8_t *out_uuid,
                                         uint8_t *out_pubkey,
                                         size_t out_pubkey_len);

// KpsKeyInfo holds metadata for a single KEM key entry.
typedef struct {
    uint8_t uuid[16];
    KmHpkeAlgorithm algorithm;
    uint8_t kem_pub_key[64];
    size_t kem_pub_key_len;
    uint8_t binding_pub_key[64];
    size_t binding_pub_key_len;
    uint64_t remaining_lifespan_secs;
} KpsKeyInfo;

// key_manager_enumerate_kem_keys enumerates all active KEM keys in the registry.
// Writes up to max_entries KpsKeyInfo structs to out_entries and sets out_count
// to the number actually written.
//
// Returns 0 on success, -1 on error.
int32_t key_manager_enumerate_kem_keys(
    KpsKeyInfo *out_entries,
    size_t max_entries,
    size_t *out_count);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif // KPS_KEY_CUSTODY_CORE_H_
