#ifndef KPS_KEY_CUSTODY_CORE_H_
#define KPS_KEY_CUSTODY_CORE_H_

/* Auto-generated by cbindgen. DO NOT EDIT. */

#include <stddef.h>
#include <stdint.h>
#include "../../../km_common/include/km_algorithms.h"

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

int32_t key_manager_generate_kem_keypair(KmHpkeAlgorithm algo,
                                         const uint8_t *binding_pubkey,
                                         size_t binding_pubkey_len,
                                         uint64_t expiry_secs,
                                         uint8_t *out_uuid,
                                         uint8_t *out_pubkey,
                                         size_t out_pubkey_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* KPS_KEY_CUSTODY_CORE_H_ */
