
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_ChangePPS  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_CHANGEPPS_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_CHANGEPPS_FP_H_

// Input structure definition
typedef struct
{
    TPMI_RH_PLATFORM authHandle;
} ChangePPS_In;

// Response code modifiers
#    define RC_ChangePPS_authHandle (TPM_RC_H + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_ChangePPS(ChangePPS_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_CHANGEPPS_FP_H_
#endif    // CC_ChangePPS
