
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_ClearControl  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_CLEARCONTROL_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_CLEARCONTROL_FP_H_

// Input structure definition
typedef struct
{
    TPMI_RH_CLEAR auth;
    TPMI_YES_NO   disable;
} ClearControl_In;

// Response code modifiers
#    define RC_ClearControl_auth    (TPM_RC_H + TPM_RC_1)
#    define RC_ClearControl_disable (TPM_RC_P + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_ClearControl(ClearControl_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_CLEARCONTROL_FP_H_
#endif    // CC_ClearControl
