
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_DictionaryAttackLockReset  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_DICTIONARYATTACKLOCKRESET_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_DICTIONARYATTACKLOCKRESET_FP_H_

// Input structure definition
typedef struct
{
    TPMI_RH_LOCKOUT lockHandle;
} DictionaryAttackLockReset_In;

// Response code modifiers
#    define RC_DictionaryAttackLockReset_lockHandle (TPM_RC_H + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_DictionaryAttackLockReset(DictionaryAttackLockReset_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_DICTIONARYATTACKLOCKRESET_FP_H_
#endif    // CC_DictionaryAttackLockReset
