
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_DictionaryAttackParameters  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_DICTIONARYATTACKPARAMETERS_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_DICTIONARYATTACKPARAMETERS_FP_H_

// Input structure definition
typedef struct
{
    TPMI_RH_LOCKOUT lockHandle;
    UINT32          newMaxTries;
    UINT32          newRecoveryTime;
    UINT32          lockoutRecovery;
} DictionaryAttackParameters_In;

// Response code modifiers
#    define RC_DictionaryAttackParameters_lockHandle      (TPM_RC_H + TPM_RC_1)
#    define RC_DictionaryAttackParameters_newMaxTries     (TPM_RC_P + TPM_RC_1)
#    define RC_DictionaryAttackParameters_newRecoveryTime (TPM_RC_P + TPM_RC_2)
#    define RC_DictionaryAttackParameters_lockoutRecovery (TPM_RC_P + TPM_RC_3)

// Function prototype
TPM_RC
TPM2_DictionaryAttackParameters(DictionaryAttackParameters_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_DICTIONARYATTACKPARAMETERS_FP_H_
#endif    // CC_DictionaryAttackParameters
