
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_ECC_Parameters  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_ECC_PARAMETERS_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_ECC_PARAMETERS_FP_H_

// Input structure definition
typedef struct
{
    TPMI_ECC_CURVE curveID;
} ECC_Parameters_In;

// Output structure definition
typedef struct
{
    TPMS_ALGORITHM_DETAIL_ECC parameters;
} ECC_Parameters_Out;

// Response code modifiers
#    define RC_ECC_Parameters_curveID (TPM_RC_P + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_ECC_Parameters(ECC_Parameters_In* in, ECC_Parameters_Out* out);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_ECC_PARAMETERS_FP_H_
#endif    // CC_ECC_Parameters
