
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_ECDH_KeyGen  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_ECDH_KEYGEN_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_ECDH_KEYGEN_FP_H_

// Input structure definition
typedef struct
{
    TPMI_DH_OBJECT keyHandle;
} ECDH_KeyGen_In;

// Output structure definition
typedef struct
{
    TPM2B_ECC_POINT zPoint;
    TPM2B_ECC_POINT pubPoint;
} ECDH_KeyGen_Out;

// Response code modifiers
#    define RC_ECDH_KeyGen_keyHandle (TPM_RC_H + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_ECDH_KeyGen(ECDH_KeyGen_In* in, ECDH_KeyGen_Out* out);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_ECDH_KEYGEN_FP_H_
#endif    // CC_ECDH_KeyGen
