
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_ECDH_ZGen  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_ECDH_ZGEN_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_ECDH_ZGEN_FP_H_

// Input structure definition
typedef struct
{
    TPMI_DH_OBJECT  keyHandle;
    TPM2B_ECC_POINT inPoint;
} ECDH_ZGen_In;

// Output structure definition
typedef struct
{
    TPM2B_ECC_POINT outPoint;
} ECDH_ZGen_Out;

// Response code modifiers
#    define RC_ECDH_ZGen_keyHandle (TPM_RC_H + TPM_RC_1)
#    define RC_ECDH_ZGen_inPoint   (TPM_RC_P + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_ECDH_ZGen(ECDH_ZGen_In* in, ECDH_ZGen_Out* out);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_ECDH_ZGEN_FP_H_
#endif    // CC_ECDH_ZGen
