
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_EvictControl  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_EVICTCONTROL_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_EVICTCONTROL_FP_H_

// Input structure definition
typedef struct
{
    TPMI_RH_PROVISION  auth;
    TPMI_DH_OBJECT     objectHandle;
    TPMI_DH_PERSISTENT persistentHandle;
} EvictControl_In;

// Response code modifiers
#    define RC_EvictControl_auth             (TPM_RC_H + TPM_RC_1)
#    define RC_EvictControl_objectHandle     (TPM_RC_H + TPM_RC_2)
#    define RC_EvictControl_persistentHandle (TPM_RC_P + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_EvictControl(EvictControl_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_EVICTCONTROL_FP_H_
#endif    // CC_EvictControl
