
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_FlushContext  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_FLUSHCONTEXT_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_FLUSHCONTEXT_FP_H_

// Input structure definition
typedef struct
{
    TPMI_DH_CONTEXT flushHandle;
} FlushContext_In;

// Response code modifiers
#    define RC_FlushContext_flushHandle (TPM_RC_P + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_FlushContext(FlushContext_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_FLUSHCONTEXT_FP_H_
#endif    // CC_FlushContext
