
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_GetTestResult  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_GETTESTRESULT_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_GETTESTRESULT_FP_H_

// Output structure definition
typedef struct
{
    TPM2B_MAX_BUFFER outData;
    TPM_RC           testResult;
} GetTestResult_Out;

// Function prototype
TPM_RC
TPM2_GetTestResult(GetTestResult_Out* out);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_GETTESTRESULT_FP_H_
#endif    // CC_GetTestResult
