
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_HashSequenceStart  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_HASHSEQUENCESTART_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_HASHSEQUENCESTART_FP_H_

// Input structure definition
typedef struct
{
    TPM2B_AUTH    auth;
    TPMI_ALG_HASH hashAlg;
} HashSequenceStart_In;

// Output structure definition
typedef struct
{
    TPMI_DH_OBJECT sequenceHandle;
} HashSequenceStart_Out;

// Response code modifiers
#    define RC_HashSequenceStart_auth    (TPM_RC_P + TPM_RC_1)
#    define RC_HashSequenceStart_hashAlg (TPM_RC_P + TPM_RC_2)

// Function prototype
TPM_RC
TPM2_HashSequenceStart(HashSequenceStart_In* in, HashSequenceStart_Out* out);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_HASHSEQUENCESTART_FP_H_
#endif    // CC_HashSequenceStart
