
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_NV_GlobalWriteLock  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_NV_GLOBALWRITELOCK_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_NV_GLOBALWRITELOCK_FP_H_

// Input structure definition
typedef struct
{
    TPMI_RH_PROVISION authHandle;
} NV_GlobalWriteLock_In;

// Response code modifiers
#    define RC_NV_GlobalWriteLock_authHandle (TPM_RC_H + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_NV_GlobalWriteLock(NV_GlobalWriteLock_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_NV_GLOBALWRITELOCK_FP_H_
#endif    // CC_NV_GlobalWriteLock
