
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_NV_Increment  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_NV_INCREMENT_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_NV_INCREMENT_FP_H_

// Input structure definition
typedef struct
{
    TPMI_RH_NV_AUTH  authHandle;
    TPMI_RH_NV_INDEX nvIndex;
} NV_Increment_In;

// Response code modifiers
#    define RC_NV_Increment_authHandle (TPM_RC_H + TPM_RC_1)
#    define RC_NV_Increment_nvIndex    (TPM_RC_H + TPM_RC_2)

// Function prototype
TPM_RC
TPM2_NV_Increment(NV_Increment_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_NV_INCREMENT_FP_H_
#endif    // CC_NV_Increment
