
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_PCR_Reset  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_PCR_RESET_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_PCR_RESET_FP_H_

// Input structure definition
typedef struct
{
    TPMI_DH_PCR pcrHandle;
} PCR_Reset_In;

// Response code modifiers
#    define RC_PCR_Reset_pcrHandle (TPM_RC_H + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_PCR_Reset(PCR_Reset_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_PCR_RESET_FP_H_
#endif    // CC_PCR_Reset
