
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_PCR_SetAuthPolicy  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_PCR_SETAUTHPOLICY_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_PCR_SETAUTHPOLICY_FP_H_

// Input structure definition
typedef struct
{
    TPMI_RH_PLATFORM authHandle;
    TPM2B_DIGEST     authPolicy;
    TPMI_ALG_HASH    hashAlg;
    TPMI_DH_PCR      pcrNum;
} PCR_SetAuthPolicy_In;

// Response code modifiers
#    define RC_PCR_SetAuthPolicy_authHandle (TPM_RC_H + TPM_RC_1)
#    define RC_PCR_SetAuthPolicy_authPolicy (TPM_RC_P + TPM_RC_1)
#    define RC_PCR_SetAuthPolicy_hashAlg    (TPM_RC_P + TPM_RC_2)
#    define RC_PCR_SetAuthPolicy_pcrNum     (TPM_RC_P + TPM_RC_3)

// Function prototype
TPM_RC
TPM2_PCR_SetAuthPolicy(PCR_SetAuthPolicy_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_PCR_SETAUTHPOLICY_FP_H_
#endif    // CC_PCR_SetAuthPolicy
