
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_PCR_Read  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_PCR_READ_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_PCR_READ_FP_H_

// Input structure definition
typedef struct
{
    TPML_PCR_SELECTION pcrSelectionIn;
} PCR_Read_In;

// Output structure definition
typedef struct
{
    UINT32             pcrUpdateCounter;
    TPML_PCR_SELECTION pcrSelectionOut;
    TPML_DIGEST        pcrValues;
} PCR_Read_Out;

// Response code modifiers
#    define RC_PCR_Read_pcrSelectionIn (TPM_RC_P + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_PCR_Read(PCR_Read_In* in, PCR_Read_Out* out);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_PCR_READ_FP_H_
#endif    // CC_PCR_Read
