
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_PCR_Allocate  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_PCR_ALLOCATE_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_PCR_ALLOCATE_FP_H_

// Input structure definition
typedef struct
{
    TPMI_RH_PLATFORM   authHandle;
    TPML_PCR_SELECTION pcrAllocation;
} PCR_Allocate_In;

// Output structure definition
typedef struct
{
    TPMI_YES_NO allocationSuccess;
    UINT32      maxPCR;
    UINT32      sizeNeeded;
    UINT32      sizeAvailable;
} PCR_Allocate_Out;

// Response code modifiers
#    define RC_PCR_Allocate_authHandle    (TPM_RC_H + TPM_RC_1)
#    define RC_PCR_Allocate_pcrAllocation (TPM_RC_P + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_PCR_Allocate(PCR_Allocate_In* in, PCR_Allocate_Out* out);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_PCR_ALLOCATE_FP_H_
#endif    // CC_PCR_Allocate
