
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_PolicyTicket  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYTICKET_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYTICKET_FP_H_

// Input structure definition
typedef struct
{
    TPMI_SH_POLICY policySession;
    TPM2B_TIMEOUT  timeout;
    TPM2B_DIGEST   cpHashA;
    TPM2B_NONCE    policyRef;
    TPM2B_NAME     authName;
    TPMT_TK_AUTH   ticket;
} PolicyTicket_In;

// Response code modifiers
#    define RC_PolicyTicket_policySession (TPM_RC_H + TPM_RC_1)
#    define RC_PolicyTicket_timeout       (TPM_RC_P + TPM_RC_1)
#    define RC_PolicyTicket_cpHashA       (TPM_RC_P + TPM_RC_2)
#    define RC_PolicyTicket_policyRef     (TPM_RC_P + TPM_RC_3)
#    define RC_PolicyTicket_authName      (TPM_RC_P + TPM_RC_4)
#    define RC_PolicyTicket_ticket        (TPM_RC_P + TPM_RC_5)

// Function prototype
TPM_RC
TPM2_PolicyTicket(PolicyTicket_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYTICKET_FP_H_
#endif    // CC_PolicyTicket
