
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_PolicyPhysicalPresence  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYPHYSICALPRESENCE_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYPHYSICALPRESENCE_FP_H_

// Input structure definition
typedef struct
{
    TPMI_SH_POLICY policySession;
} PolicyPhysicalPresence_In;

// Response code modifiers
#    define RC_PolicyPhysicalPresence_policySession (TPM_RC_H + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_PolicyPhysicalPresence(PolicyPhysicalPresence_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYPHYSICALPRESENCE_FP_H_
#endif    // CC_PolicyPhysicalPresence
