
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_PolicyRestart  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYRESTART_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYRESTART_FP_H_

// Input structure definition
typedef struct
{
    TPMI_SH_POLICY sessionHandle;
} PolicyRestart_In;

// Response code modifiers
#    define RC_PolicyRestart_sessionHandle (TPM_RC_H + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_PolicyRestart(PolicyRestart_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYRESTART_FP_H_
#endif    // CC_PolicyRestart
