
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_PolicyNameHash  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYNAMEHASH_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYNAMEHASH_FP_H_

// Input structure definition
typedef struct
{
    TPMI_SH_POLICY policySession;
    TPM2B_DIGEST   nameHash;
} PolicyNameHash_In;

// Response code modifiers
#    define RC_PolicyNameHash_policySession (TPM_RC_H + TPM_RC_1)
#    define RC_PolicyNameHash_nameHash      (TPM_RC_P + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_PolicyNameHash(PolicyNameHash_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYNAMEHASH_FP_H_
#endif    // CC_PolicyNameHash
