
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_PolicyAuthorizeNV  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYAUTHORIZENV_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYAUTHORIZENV_FP_H_

// Input structure definition
typedef struct
{
    TPMI_RH_NV_AUTH  authHandle;
    TPMI_RH_NV_INDEX nvIndex;
    TPMI_SH_POLICY   policySession;
} PolicyAuthorizeNV_In;

// Response code modifiers
#    define RC_PolicyAuthorizeNV_authHandle    (TPM_RC_H + TPM_RC_1)
#    define RC_PolicyAuthorizeNV_nvIndex       (TPM_RC_H + TPM_RC_2)
#    define RC_PolicyAuthorizeNV_policySession (TPM_RC_H + TPM_RC_3)

// Function prototype
TPM_RC
TPM2_PolicyAuthorizeNV(PolicyAuthorizeNV_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYAUTHORIZENV_FP_H_
#endif    // CC_PolicyAuthorizeNV
