
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_PolicyCommandCode  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYCOMMANDCODE_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYCOMMANDCODE_FP_H_

// Input structure definition
typedef struct
{
    TPMI_SH_POLICY policySession;
    TPM_CC         code;
} PolicyCommandCode_In;

// Response code modifiers
#    define RC_PolicyCommandCode_policySession (TPM_RC_H + TPM_RC_1)
#    define RC_PolicyCommandCode_code          (TPM_RC_P + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_PolicyCommandCode(PolicyCommandCode_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYCOMMANDCODE_FP_H_
#endif    // CC_PolicyCommandCode
