
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_PolicyParameters  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYPARAMETERS_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYPARAMETERS_FP_H_

// Input structure definition
typedef struct
{
    TPMI_SH_POLICY policySession;
    TPM2B_DIGEST   pHash;
} PolicyParameters_In;

// Response code modifiers
#    define RC_PolicyParameters_policySession (TPM_RC_H + TPM_RC_1)
#    define RC_PolicyParameters_pHash         (TPM_RC_P + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_PolicyParameters(PolicyParameters_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_POLICYPARAMETERS_FP_H_
#endif    // CC_PolicyParameters
