
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_ReadPublic  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_READPUBLIC_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_READPUBLIC_FP_H_

// Input structure definition
typedef struct
{
    TPMI_DH_OBJECT objectHandle;
} ReadPublic_In;

// Output structure definition
typedef struct
{
    TPM2B_PUBLIC outPublic;
    TPM2B_NAME   name;
    TPM2B_NAME   qualifiedName;
} ReadPublic_Out;

// Response code modifiers
#    define RC_ReadPublic_objectHandle (TPM_RC_H + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_ReadPublic(ReadPublic_In* in, ReadPublic_Out* out);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_READPUBLIC_FP_H_
#endif    // CC_ReadPublic
