
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_ReadClock  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_READCLOCK_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_READCLOCK_FP_H_

// Output structure definition
typedef struct
{
    TPMS_TIME_INFO currentTime;
} ReadClock_Out;

// Function prototype
TPM_RC
TPM2_ReadClock(ReadClock_Out* out);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_READCLOCK_FP_H_
#endif    // CC_ReadClock
