
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_SelfTest  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_SELFTEST_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_SELFTEST_FP_H_

// Input structure definition
typedef struct
{
    TPMI_YES_NO fullTest;
} SelfTest_In;

// Response code modifiers
#    define RC_SelfTest_fullTest (TPM_RC_P + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_SelfTest(SelfTest_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_SELFTEST_FP_H_
#endif    // CC_SelfTest
