
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_SequenceComplete  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_SEQUENCECOMPLETE_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_SEQUENCECOMPLETE_FP_H_

// Input structure definition
typedef struct
{
    TPMI_DH_OBJECT    sequenceHandle;
    TPM2B_MAX_BUFFER  buffer;
    TPMI_RH_HIERARCHY hierarchy;
} SequenceComplete_In;

// Output structure definition
typedef struct
{
    TPM2B_DIGEST      result;
    TPMT_TK_HASHCHECK validation;
} SequenceComplete_Out;

// Response code modifiers
#    define RC_SequenceComplete_sequenceHandle (TPM_RC_H + TPM_RC_1)
#    define RC_SequenceComplete_buffer         (TPM_RC_P + TPM_RC_1)
#    define RC_SequenceComplete_hierarchy      (TPM_RC_P + TPM_RC_2)

// Function prototype
TPM_RC
TPM2_SequenceComplete(SequenceComplete_In* in, SequenceComplete_Out* out);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_SEQUENCECOMPLETE_FP_H_
#endif    // CC_SequenceComplete
