
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_SetAlgorithmSet  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_SETALGORITHMSET_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_SETALGORITHMSET_FP_H_

// Input structure definition
typedef struct
{
    TPMI_RH_PLATFORM authHandle;
    UINT32           algorithmSet;
} SetAlgorithmSet_In;

// Response code modifiers
#    define RC_SetAlgorithmSet_authHandle   (TPM_RC_H + TPM_RC_1)
#    define RC_SetAlgorithmSet_algorithmSet (TPM_RC_P + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_SetAlgorithmSet(SetAlgorithmSet_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_SETALGORITHMSET_FP_H_
#endif    // CC_SetAlgorithmSet
