
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_SetCommandCodeAuditStatus  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_SETCOMMANDCODEAUDITSTATUS_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_SETCOMMANDCODEAUDITSTATUS_FP_H_

// Input structure definition
typedef struct
{
    TPMI_RH_PROVISION auth;
    TPMI_ALG_HASH     auditAlg;
    TPML_CC           setList;
    TPML_CC           clearList;
} SetCommandCodeAuditStatus_In;

// Response code modifiers
#    define RC_SetCommandCodeAuditStatus_auth      (TPM_RC_H + TPM_RC_1)
#    define RC_SetCommandCodeAuditStatus_auditAlg  (TPM_RC_P + TPM_RC_1)
#    define RC_SetCommandCodeAuditStatus_setList   (TPM_RC_P + TPM_RC_2)
#    define RC_SetCommandCodeAuditStatus_clearList (TPM_RC_P + TPM_RC_3)

// Function prototype
TPM_RC
TPM2_SetCommandCodeAuditStatus(SetCommandCodeAuditStatus_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_SETCOMMANDCODEAUDITSTATUS_FP_H_
#endif    // CC_SetCommandCodeAuditStatus
