
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#if CC_StirRandom  // Command must be enabled

#  ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_STIRRANDOM_FP_H_
#    define _TPM_INCLUDE_PRIVATE_PROTOTYPES_STIRRANDOM_FP_H_

// Input structure definition
typedef struct
{
    TPM2B_SENSITIVE_DATA inData;
} StirRandom_In;

// Response code modifiers
#    define RC_StirRandom_inData (TPM_RC_P + TPM_RC_1)

// Function prototype
TPM_RC
TPM2_StirRandom(StirRandom_In* in);

#  endif  // _TPM_INCLUDE_PRIVATE_PROTOTYPES_STIRRANDOM_FP_H_
#endif    // CC_StirRandom
