user  nginx;
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        location /demodata/ {
            alias /usr/share/nginx/html/demodata/;
            autoindex on;
        }
    }
}
