// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: launcher/teeserver/teeserver.proto

package teeserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TeeServer_GetToken_FullMethodName               = "/teeserver.TeeServer/GetToken"
	TeeServer_GetITAToken_FullMethodName            = "/teeserver.TeeServer/GetITAToken"
	TeeServer_GetAttestationEvidence_FullMethodName = "/teeserver.TeeServer/GetAttestationEvidence"
	TeeServer_GetKeyEndorsement_FullMethodName      = "/teeserver.TeeServer/GetKeyEndorsement"
)

// TeeServerClient is the client API for TeeServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TeeServerClient interface {
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error)
	GetITAToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error)
	GetAttestationEvidence(ctx context.Context, in *GetAttestationEvidenceRequest, opts ...grpc.CallOption) (*GetAttestationEvidenceResponse, error)
	GetKeyEndorsement(ctx context.Context, in *GetKeyEndorsementRequest, opts ...grpc.CallOption) (*GetKeyEndorsementResponse, error)
}

type teeServerClient struct {
	cc grpc.ClientConnInterface
}

func NewTeeServerClient(cc grpc.ClientConnInterface) TeeServerClient {
	return &teeServerClient{cc}
}

func (c *teeServerClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenResponse)
	err := c.cc.Invoke(ctx, TeeServer_GetToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teeServerClient) GetITAToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenResponse)
	err := c.cc.Invoke(ctx, TeeServer_GetITAToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teeServerClient) GetAttestationEvidence(ctx context.Context, in *GetAttestationEvidenceRequest, opts ...grpc.CallOption) (*GetAttestationEvidenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttestationEvidenceResponse)
	err := c.cc.Invoke(ctx, TeeServer_GetAttestationEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teeServerClient) GetKeyEndorsement(ctx context.Context, in *GetKeyEndorsementRequest, opts ...grpc.CallOption) (*GetKeyEndorsementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyEndorsementResponse)
	err := c.cc.Invoke(ctx, TeeServer_GetKeyEndorsement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeeServerServer is the server API for TeeServer service.
// All implementations must embed UnimplementedTeeServerServer
// for forward compatibility.
type TeeServerServer interface {
	GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error)
	GetITAToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error)
	GetAttestationEvidence(context.Context, *GetAttestationEvidenceRequest) (*GetAttestationEvidenceResponse, error)
	GetKeyEndorsement(context.Context, *GetKeyEndorsementRequest) (*GetKeyEndorsementResponse, error)
	mustEmbedUnimplementedTeeServerServer()
}

// UnimplementedTeeServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTeeServerServer struct{}

func (UnimplementedTeeServerServer) GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToken not implemented")
}
func (UnimplementedTeeServerServer) GetITAToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetITAToken not implemented")
}
func (UnimplementedTeeServerServer) GetAttestationEvidence(context.Context, *GetAttestationEvidenceRequest) (*GetAttestationEvidenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAttestationEvidence not implemented")
}
func (UnimplementedTeeServerServer) GetKeyEndorsement(context.Context, *GetKeyEndorsementRequest) (*GetKeyEndorsementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKeyEndorsement not implemented")
}
func (UnimplementedTeeServerServer) mustEmbedUnimplementedTeeServerServer() {}
func (UnimplementedTeeServerServer) testEmbeddedByValue()                   {}

// UnsafeTeeServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeeServerServer will
// result in compilation errors.
type UnsafeTeeServerServer interface {
	mustEmbedUnimplementedTeeServerServer()
}

func RegisterTeeServerServer(s grpc.ServiceRegistrar, srv TeeServerServer) {
	// If the following call panics, it indicates UnimplementedTeeServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TeeServer_ServiceDesc, srv)
}

func _TeeServer_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeeServerServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeeServer_GetToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeeServerServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeeServer_GetITAToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeeServerServer).GetITAToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeeServer_GetITAToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeeServerServer).GetITAToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeeServer_GetAttestationEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttestationEvidenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeeServerServer).GetAttestationEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeeServer_GetAttestationEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeeServerServer).GetAttestationEvidence(ctx, req.(*GetAttestationEvidenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeeServer_GetKeyEndorsement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyEndorsementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeeServerServer).GetKeyEndorsement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeeServer_GetKeyEndorsement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeeServerServer).GetKeyEndorsement(ctx, req.(*GetKeyEndorsementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TeeServer_ServiceDesc is the grpc.ServiceDesc for TeeServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeeServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "teeserver.TeeServer",
	HandlerType: (*TeeServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetToken",
			Handler:    _TeeServer_GetToken_Handler,
		},
		{
			MethodName: "GetITAToken",
			Handler:    _TeeServer_GetITAToken_Handler,
		},
		{
			MethodName: "GetAttestationEvidence",
			Handler:    _TeeServer_GetAttestationEvidence_Handler,
		},
		{
			MethodName: "GetKeyEndorsement",
			Handler:    _TeeServer_GetKeyEndorsement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "launcher/teeserver/teeserver.proto",
}
