// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: launcher/teeserver/teeserver.proto

package teeserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContainerImageSignatures represents the configuration for AllowedPrincipalTags for
// ContainerImageSignature claims
type ContainerImageSignatures struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyIds        []string               `protobuf:"bytes,1,rep,name=key_ids,proto3" json:"key_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerImageSignatures) Reset() {
	*x = ContainerImageSignatures{}
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerImageSignatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerImageSignatures) ProtoMessage() {}

func (x *ContainerImageSignatures) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerImageSignatures.ProtoReflect.Descriptor instead.
func (*ContainerImageSignatures) Descriptor() ([]byte, []int) {
	return file_launcher_teeserver_teeserver_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerImageSignatures) GetKeyIds() []string {
	if x != nil {
		return x.KeyIds
	}
	return nil
}

// AllowedPrincipalTags allows for requestors to configure what principal tags are contained in the
// resulting GCA token.
type AllowedPrincipalTags struct {
	state                    protoimpl.MessageState    `protogen:"open.v1"`
	ContainerImageSignatures *ContainerImageSignatures `protobuf:"bytes,1,opt,name=container_image_signatures,proto3" json:"container_image_signatures,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AllowedPrincipalTags) Reset() {
	*x = AllowedPrincipalTags{}
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowedPrincipalTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowedPrincipalTags) ProtoMessage() {}

func (x *AllowedPrincipalTags) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowedPrincipalTags.ProtoReflect.Descriptor instead.
func (*AllowedPrincipalTags) Descriptor() ([]byte, []int) {
	return file_launcher_teeserver_teeserver_proto_rawDescGZIP(), []int{1}
}

func (x *AllowedPrincipalTags) GetContainerImageSignatures() *ContainerImageSignatures {
	if x != nil {
		return x.ContainerImageSignatures
	}
	return nil
}

// AWSPrincipalTagsOptions represents the options for the AWSPrincipalTag token type.
type AWSPrincipalTagsOptions struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AllowedPrincipalTags *AllowedPrincipalTags  `protobuf:"bytes,1,opt,name=allowed_principal_tags,proto3" json:"allowed_principal_tags,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AWSPrincipalTagsOptions) Reset() {
	*x = AWSPrincipalTagsOptions{}
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AWSPrincipalTagsOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AWSPrincipalTagsOptions) ProtoMessage() {}

func (x *AWSPrincipalTagsOptions) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AWSPrincipalTagsOptions.ProtoReflect.Descriptor instead.
func (*AWSPrincipalTagsOptions) Descriptor() ([]byte, []int) {
	return file_launcher_teeserver_teeserver_proto_rawDescGZIP(), []int{2}
}

func (x *AWSPrincipalTagsOptions) GetAllowedPrincipalTags() *AllowedPrincipalTags {
	if x != nil {
		return x.AllowedPrincipalTags
	}
	return nil
}

// TokenOptions contains fields that will be passed to the Attestation Service TokenOptions field.
type TokenOptions struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	Audience               string                   `protobuf:"bytes,1,opt,name=audience,proto3" json:"audience,omitempty"`
	Nonces                 []string                 `protobuf:"bytes,2,rep,name=nonces,proto3" json:"nonces,omitempty"`
	TokenType              string                   `protobuf:"bytes,3,opt,name=token_type,proto3" json:"token_type,omitempty"`
	AwsPrincipalTagOptions *AWSPrincipalTagsOptions `protobuf:"bytes,4,opt,name=aws_principal_tag_options,proto3" json:"aws_principal_tag_options,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TokenOptions) Reset() {
	*x = TokenOptions{}
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenOptions) ProtoMessage() {}

func (x *TokenOptions) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenOptions.ProtoReflect.Descriptor instead.
func (*TokenOptions) Descriptor() ([]byte, []int) {
	return file_launcher_teeserver_teeserver_proto_rawDescGZIP(), []int{3}
}

func (x *TokenOptions) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *TokenOptions) GetNonces() []string {
	if x != nil {
		return x.Nonces
	}
	return nil
}

func (x *TokenOptions) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenOptions) GetAwsPrincipalTagOptions() *AWSPrincipalTagsOptions {
	if x != nil {
		return x.AwsPrincipalTagOptions
	}
	return nil
}

type GetTokenRequest struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	Audience               string                   `protobuf:"bytes,1,opt,name=audience,proto3" json:"audience,omitempty"`
	Nonces                 []string                 `protobuf:"bytes,2,rep,name=nonces,proto3" json:"nonces,omitempty"`
	TokenType              string                   `protobuf:"bytes,3,opt,name=token_type,proto3" json:"token_type,omitempty"`
	AwsPrincipalTagOptions *AWSPrincipalTagsOptions `protobuf:"bytes,4,opt,name=aws_principal_tag_options,proto3" json:"aws_principal_tag_options,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_launcher_teeserver_teeserver_proto_rawDescGZIP(), []int{4}
}

func (x *GetTokenRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *GetTokenRequest) GetNonces() []string {
	if x != nil {
		return x.Nonces
	}
	return nil
}

func (x *GetTokenRequest) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *GetTokenRequest) GetAwsPrincipalTagOptions() *AWSPrincipalTagsOptions {
	if x != nil {
		return x.AwsPrincipalTagOptions
	}
	return nil
}

type GetTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenResponse) Reset() {
	*x = GetTokenResponse{}
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenResponse) ProtoMessage() {}

func (x *GetTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenResponse.ProtoReflect.Descriptor instead.
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return file_launcher_teeserver_teeserver_proto_rawDescGZIP(), []int{5}
}

func (x *GetTokenResponse) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type GetAttestationEvidenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     []byte                 `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttestationEvidenceRequest) Reset() {
	*x = GetAttestationEvidenceRequest{}
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttestationEvidenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttestationEvidenceRequest) ProtoMessage() {}

func (x *GetAttestationEvidenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttestationEvidenceRequest.ProtoReflect.Descriptor instead.
func (*GetAttestationEvidenceRequest) Descriptor() ([]byte, []int) {
	return file_launcher_teeserver_teeserver_proto_rawDescGZIP(), []int{6}
}

func (x *GetAttestationEvidenceRequest) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

type GetAttestationEvidenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evidence      []byte                 `protobuf:"bytes,1,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttestationEvidenceResponse) Reset() {
	*x = GetAttestationEvidenceResponse{}
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttestationEvidenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttestationEvidenceResponse) ProtoMessage() {}

func (x *GetAttestationEvidenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttestationEvidenceResponse.ProtoReflect.Descriptor instead.
func (*GetAttestationEvidenceResponse) Descriptor() ([]byte, []int) {
	return file_launcher_teeserver_teeserver_proto_rawDescGZIP(), []int{7}
}

func (x *GetAttestationEvidenceResponse) GetEvidence() []byte {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type KeyHandle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyHandle) Reset() {
	*x = KeyHandle{}
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyHandle) ProtoMessage() {}

func (x *KeyHandle) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyHandle.ProtoReflect.Descriptor instead.
func (*KeyHandle) Descriptor() ([]byte, []int) {
	return file_launcher_teeserver_teeserver_proto_rawDescGZIP(), []int{8}
}

func (x *KeyHandle) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type GetKeyEndorsementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     []byte                 `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	KeyHandle     *KeyHandle             `protobuf:"bytes,2,opt,name=key_handle,proto3" json:"key_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyEndorsementRequest) Reset() {
	*x = GetKeyEndorsementRequest{}
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyEndorsementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyEndorsementRequest) ProtoMessage() {}

func (x *GetKeyEndorsementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyEndorsementRequest.ProtoReflect.Descriptor instead.
func (*GetKeyEndorsementRequest) Descriptor() ([]byte, []int) {
	return file_launcher_teeserver_teeserver_proto_rawDescGZIP(), []int{9}
}

func (x *GetKeyEndorsementRequest) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *GetKeyEndorsementRequest) GetKeyHandle() *KeyHandle {
	if x != nil {
		return x.KeyHandle
	}
	return nil
}

type GetKeyEndorsementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endorsement   []byte                 `protobuf:"bytes,1,opt,name=endorsement,proto3" json:"endorsement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyEndorsementResponse) Reset() {
	*x = GetKeyEndorsementResponse{}
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyEndorsementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyEndorsementResponse) ProtoMessage() {}

func (x *GetKeyEndorsementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_teeserver_teeserver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyEndorsementResponse.ProtoReflect.Descriptor instead.
func (*GetKeyEndorsementResponse) Descriptor() ([]byte, []int) {
	return file_launcher_teeserver_teeserver_proto_rawDescGZIP(), []int{10}
}

func (x *GetKeyEndorsementResponse) GetEndorsement() []byte {
	if x != nil {
		return x.Endorsement
	}
	return nil
}

var File_launcher_teeserver_teeserver_proto protoreflect.FileDescriptor

const file_launcher_teeserver_teeserver_proto_rawDesc = "" +
	"\n" +
	"\"launcher/teeserver/teeserver.proto\x12\tteeserver\"4\n" +
	"\x18ContainerImageSignatures\x12\x18\n" +
	"\akey_ids\x18\x01 \x03(\tR\akey_ids\"{\n" +
	"\x14AllowedPrincipalTags\x12c\n" +
	"\x1acontainer_image_signatures\x18\x01 \x01(\v2#.teeserver.ContainerImageSignaturesR\x1acontainer_image_signatures\"r\n" +
	"\x17AWSPrincipalTagsOptions\x12W\n" +
	"\x16allowed_principal_tags\x18\x01 \x01(\v2\x1f.teeserver.AllowedPrincipalTagsR\x16allowed_principal_tags\"\xc4\x01\n" +
	"\fTokenOptions\x12\x1a\n" +
	"\baudience\x18\x01 \x01(\tR\baudience\x12\x16\n" +
	"\x06nonces\x18\x02 \x03(\tR\x06nonces\x12\x1e\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\n" +
	"token_type\x12`\n" +
	"\x19aws_principal_tag_options\x18\x04 \x01(\v2\".teeserver.AWSPrincipalTagsOptionsR\x19aws_principal_tag_options\"\xc7\x01\n" +
	"\x0fGetTokenRequest\x12\x1a\n" +
	"\baudience\x18\x01 \x01(\tR\baudience\x12\x16\n" +
	"\x06nonces\x18\x02 \x03(\tR\x06nonces\x12\x1e\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\n" +
	"token_type\x12`\n" +
	"\x19aws_principal_tag_options\x18\x04 \x01(\v2\".teeserver.AWSPrincipalTagsOptionsR\x19aws_principal_tag_options\"(\n" +
	"\x10GetTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\"=\n" +
	"\x1dGetAttestationEvidenceRequest\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\fR\tchallenge\"<\n" +
	"\x1eGetAttestationEvidenceResponse\x12\x1a\n" +
	"\bevidence\x18\x01 \x01(\fR\bevidence\"#\n" +
	"\tKeyHandle\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\"n\n" +
	"\x18GetKeyEndorsementRequest\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\fR\tchallenge\x124\n" +
	"\n" +
	"key_handle\x18\x02 \x01(\v2\x14.teeserver.KeyHandleR\n" +
	"key_handle\"=\n" +
	"\x19GetKeyEndorsementResponse\x12 \n" +
	"\vendorsement\x18\x01 \x01(\fR\vendorsement2\xe7\x02\n" +
	"\tTeeServer\x12C\n" +
	"\bGetToken\x12\x1a.teeserver.GetTokenRequest\x1a\x1b.teeserver.GetTokenResponse\x12F\n" +
	"\vGetITAToken\x12\x1a.teeserver.GetTokenRequest\x1a\x1b.teeserver.GetTokenResponse\x12m\n" +
	"\x16GetAttestationEvidence\x12(.teeserver.GetAttestationEvidenceRequest\x1a).teeserver.GetAttestationEvidenceResponse\x12^\n" +
	"\x11GetKeyEndorsement\x12#.teeserver.GetKeyEndorsementRequest\x1a$.teeserver.GetKeyEndorsementResponseB3Z1github.com/google/go-tpm-tools/launcher/teeserverb\x06proto3"

var (
	file_launcher_teeserver_teeserver_proto_rawDescOnce sync.Once
	file_launcher_teeserver_teeserver_proto_rawDescData []byte
)

func file_launcher_teeserver_teeserver_proto_rawDescGZIP() []byte {
	file_launcher_teeserver_teeserver_proto_rawDescOnce.Do(func() {
		file_launcher_teeserver_teeserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_launcher_teeserver_teeserver_proto_rawDesc), len(file_launcher_teeserver_teeserver_proto_rawDesc)))
	})
	return file_launcher_teeserver_teeserver_proto_rawDescData
}

var file_launcher_teeserver_teeserver_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_launcher_teeserver_teeserver_proto_goTypes = []any{
	(*ContainerImageSignatures)(nil),       // 0: teeserver.ContainerImageSignatures
	(*AllowedPrincipalTags)(nil),           // 1: teeserver.AllowedPrincipalTags
	(*AWSPrincipalTagsOptions)(nil),        // 2: teeserver.AWSPrincipalTagsOptions
	(*TokenOptions)(nil),                   // 3: teeserver.TokenOptions
	(*GetTokenRequest)(nil),                // 4: teeserver.GetTokenRequest
	(*GetTokenResponse)(nil),               // 5: teeserver.GetTokenResponse
	(*GetAttestationEvidenceRequest)(nil),  // 6: teeserver.GetAttestationEvidenceRequest
	(*GetAttestationEvidenceResponse)(nil), // 7: teeserver.GetAttestationEvidenceResponse
	(*KeyHandle)(nil),                      // 8: teeserver.KeyHandle
	(*GetKeyEndorsementRequest)(nil),       // 9: teeserver.GetKeyEndorsementRequest
	(*GetKeyEndorsementResponse)(nil),      // 10: teeserver.GetKeyEndorsementResponse
}
var file_launcher_teeserver_teeserver_proto_depIdxs = []int32{
	0,  // 0: teeserver.AllowedPrincipalTags.container_image_signatures:type_name -> teeserver.ContainerImageSignatures
	1,  // 1: teeserver.AWSPrincipalTagsOptions.allowed_principal_tags:type_name -> teeserver.AllowedPrincipalTags
	2,  // 2: teeserver.TokenOptions.aws_principal_tag_options:type_name -> teeserver.AWSPrincipalTagsOptions
	2,  // 3: teeserver.GetTokenRequest.aws_principal_tag_options:type_name -> teeserver.AWSPrincipalTagsOptions
	8,  // 4: teeserver.GetKeyEndorsementRequest.key_handle:type_name -> teeserver.KeyHandle
	4,  // 5: teeserver.TeeServer.GetToken:input_type -> teeserver.GetTokenRequest
	4,  // 6: teeserver.TeeServer.GetITAToken:input_type -> teeserver.GetTokenRequest
	6,  // 7: teeserver.TeeServer.GetAttestationEvidence:input_type -> teeserver.GetAttestationEvidenceRequest
	9,  // 8: teeserver.TeeServer.GetKeyEndorsement:input_type -> teeserver.GetKeyEndorsementRequest
	5,  // 9: teeserver.TeeServer.GetToken:output_type -> teeserver.GetTokenResponse
	5,  // 10: teeserver.TeeServer.GetITAToken:output_type -> teeserver.GetTokenResponse
	7,  // 11: teeserver.TeeServer.GetAttestationEvidence:output_type -> teeserver.GetAttestationEvidenceResponse
	10, // 12: teeserver.TeeServer.GetKeyEndorsement:output_type -> teeserver.GetKeyEndorsementResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_launcher_teeserver_teeserver_proto_init() }
func file_launcher_teeserver_teeserver_proto_init() {
	if File_launcher_teeserver_teeserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_launcher_teeserver_teeserver_proto_rawDesc), len(file_launcher_teeserver_teeserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_launcher_teeserver_teeserver_proto_goTypes,
		DependencyIndexes: file_launcher_teeserver_teeserver_proto_depIdxs,
		MessageInfos:      file_launcher_teeserver_teeserver_proto_msgTypes,
	}.Build()
	File_launcher_teeserver_teeserver_proto = out.File
	file_launcher_teeserver_teeserver_proto_goTypes = nil
	file_launcher_teeserver_teeserver_proto_depIdxs = nil
}
