// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tpm.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Enum values come from TCG Algorithm Registry - v1.27 - Table 3
type ObjectType int32

const (
	ObjectType_OBJECT_INVALID ObjectType = 0
	ObjectType_RSA            ObjectType = 1
	ObjectType_ECC            ObjectType = 35
)

var ObjectType_name = map[int32]string{
	0:  "OBJECT_INVALID",
	1:  "RSA",
	35: "ECC",
}

var ObjectType_value = map[string]int32{
	"OBJECT_INVALID": 0,
	"RSA":            1,
	"ECC":            35,
}

func (x ObjectType) String() string {
	return proto.EnumName(ObjectType_name, int32(x))
}

func (ObjectType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_63ac7bc02f9d1279, []int{0}
}

type HashAlgo int32

const (
	HashAlgo_HASH_INVALID HashAlgo = 0
	HashAlgo_SHA256       HashAlgo = 11
)

var HashAlgo_name = map[int32]string{
	0:  "HASH_INVALID",
	11: "SHA256",
}

var HashAlgo_value = map[string]int32{
	"HASH_INVALID": 0,
	"SHA256":       11,
}

func (x HashAlgo) String() string {
	return proto.EnumName(HashAlgo_name, int32(x))
}

func (HashAlgo) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_63ac7bc02f9d1279, []int{1}
}

// SealedBytes stores the result of a TPM2_Seal. The private portion (priv) has
// already been encrypted and is no longer sensitive. The hash algorithm is
// assumed to be SHA256.
type SealedBytes struct {
	Priv                 []byte     `protobuf:"bytes,1,opt,name=priv,proto3" json:"priv,omitempty"`
	Pub                  []byte     `protobuf:"bytes,2,opt,name=pub,proto3" json:"pub,omitempty"`
	Pcrs                 []int32    `protobuf:"varint,3,rep,packed,name=pcrs,proto3" json:"pcrs,omitempty"`
	Hash                 HashAlgo   `protobuf:"varint,4,opt,name=hash,proto3,enum=proto.HashAlgo" json:"hash,omitempty"`
	Srk                  ObjectType `protobuf:"varint,5,opt,name=srk,proto3,enum=proto.ObjectType" json:"srk,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SealedBytes) Reset()         { *m = SealedBytes{} }
func (m *SealedBytes) String() string { return proto.CompactTextString(m) }
func (*SealedBytes) ProtoMessage()    {}
func (*SealedBytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_63ac7bc02f9d1279, []int{0}
}

func (m *SealedBytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SealedBytes.Unmarshal(m, b)
}
func (m *SealedBytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SealedBytes.Marshal(b, m, deterministic)
}
func (m *SealedBytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SealedBytes.Merge(m, src)
}
func (m *SealedBytes) XXX_Size() int {
	return xxx_messageInfo_SealedBytes.Size(m)
}
func (m *SealedBytes) XXX_DiscardUnknown() {
	xxx_messageInfo_SealedBytes.DiscardUnknown(m)
}

var xxx_messageInfo_SealedBytes proto.InternalMessageInfo

func (m *SealedBytes) GetPriv() []byte {
	if m != nil {
		return m.Priv
	}
	return nil
}

func (m *SealedBytes) GetPub() []byte {
	if m != nil {
		return m.Pub
	}
	return nil
}

func (m *SealedBytes) GetPcrs() []int32 {
	if m != nil {
		return m.Pcrs
	}
	return nil
}

func (m *SealedBytes) GetHash() HashAlgo {
	if m != nil {
		return m.Hash
	}
	return HashAlgo_HASH_INVALID
}

func (m *SealedBytes) GetSrk() ObjectType {
	if m != nil {
		return m.Srk
	}
	return ObjectType_OBJECT_INVALID
}

type ImportBlob struct {
	Duplicate            []byte   `protobuf:"bytes,1,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	EncryptedSeed        []byte   `protobuf:"bytes,2,opt,name=encrypted_seed,json=encryptedSeed,proto3" json:"encrypted_seed,omitempty"`
	PublicArea           []byte   `protobuf:"bytes,3,opt,name=public_area,json=publicArea,proto3" json:"public_area,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportBlob) Reset()         { *m = ImportBlob{} }
func (m *ImportBlob) String() string { return proto.CompactTextString(m) }
func (*ImportBlob) ProtoMessage()    {}
func (*ImportBlob) Descriptor() ([]byte, []int) {
	return fileDescriptor_63ac7bc02f9d1279, []int{1}
}

func (m *ImportBlob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportBlob.Unmarshal(m, b)
}
func (m *ImportBlob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportBlob.Marshal(b, m, deterministic)
}
func (m *ImportBlob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportBlob.Merge(m, src)
}
func (m *ImportBlob) XXX_Size() int {
	return xxx_messageInfo_ImportBlob.Size(m)
}
func (m *ImportBlob) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportBlob.DiscardUnknown(m)
}

var xxx_messageInfo_ImportBlob proto.InternalMessageInfo

func (m *ImportBlob) GetDuplicate() []byte {
	if m != nil {
		return m.Duplicate
	}
	return nil
}

func (m *ImportBlob) GetEncryptedSeed() []byte {
	if m != nil {
		return m.EncryptedSeed
	}
	return nil
}

func (m *ImportBlob) GetPublicArea() []byte {
	if m != nil {
		return m.PublicArea
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.ObjectType", ObjectType_name, ObjectType_value)
	proto.RegisterEnum("proto.HashAlgo", HashAlgo_name, HashAlgo_value)
	proto.RegisterType((*SealedBytes)(nil), "proto.SealedBytes")
	proto.RegisterType((*ImportBlob)(nil), "proto.ImportBlob")
}

func init() { proto.RegisterFile("tpm.proto", fileDescriptor_63ac7bc02f9d1279) }

var fileDescriptor_63ac7bc02f9d1279 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xc1, 0x4b, 0x02, 0x41,
	0x14, 0xc6, 0xdb, 0x46, 0x2d, 0x9f, 0x66, 0xd3, 0x3b, 0xcd, 0x21, 0x48, 0x94, 0x60, 0xf1, 0xe0,
	0xc1, 0xa8, 0xfb, 0x68, 0xc2, 0x1a, 0x91, 0xb0, 0x2b, 0x5d, 0x65, 0x76, 0xf7, 0x91, 0xd6, 0xda,
	0x0e, 0x33, 0x63, 0xe0, 0x9f, 0xd1, 0x7f, 0x1c, 0x8e, 0x5b, 0x76, 0x9a, 0x8f, 0xdf, 0xfb, 0xc1,
	0x7c, 0x1f, 0x34, 0x9d, 0xde, 0x0c, 0xb5, 0x29, 0x5d, 0x89, 0x75, 0xff, 0xf4, 0xbe, 0x03, 0x68,
	0x25, 0xa4, 0x0a, 0xca, 0xc7, 0x3b, 0x47, 0x16, 0x11, 0x6a, 0xda, 0xac, 0xbf, 0x44, 0xd0, 0x0d,
	0xc2, 0x76, 0xec, 0x33, 0x72, 0x60, 0x7a, 0x9b, 0x8a, 0x53, 0x8f, 0xf6, 0xd1, 0x5b, 0x99, 0xb1,
	0x82, 0x75, 0x59, 0x58, 0x8f, 0x7d, 0xc6, 0x3e, 0xd4, 0x56, 0xca, 0xae, 0x44, 0xad, 0x1b, 0x84,
	0x9d, 0xd1, 0xe5, 0xe1, 0x9b, 0x61, 0xa4, 0xec, 0x4a, 0x16, 0x6f, 0x65, 0xec, 0x8f, 0xd8, 0x07,
	0x66, 0xcd, 0x87, 0xa8, 0x7b, 0xe7, 0xaa, 0x72, 0xe6, 0xe9, 0x3b, 0x65, 0x6e, 0xb1, 0xd3, 0x14,
	0xef, 0xaf, 0x3d, 0x03, 0x30, 0xdb, 0xe8, 0xd2, 0xb8, 0x71, 0x51, 0xa6, 0x78, 0x0d, 0xcd, 0x7c,
	0xab, 0x8b, 0x75, 0xa6, 0x1c, 0x55, 0xb5, 0x8e, 0x00, 0x6f, 0xa1, 0x43, 0x9f, 0x99, 0xd9, 0x69,
	0x47, 0xf9, 0xd2, 0x12, 0xe5, 0x55, 0xcd, 0x8b, 0x3f, 0x9a, 0x10, 0xe5, 0x78, 0x03, 0x2d, 0xbd,
	0x4d, 0x8b, 0x75, 0xb6, 0x54, 0x86, 0x94, 0x60, 0xde, 0x81, 0x03, 0x92, 0x86, 0xd4, 0x60, 0x04,
	0x70, 0xac, 0x81, 0x08, 0x9d, 0xf9, 0xf8, 0x69, 0x3a, 0x59, 0x2c, 0x67, 0x2f, 0xaf, 0xf2, 0x79,
	0xf6, 0xc8, 0x4f, 0xf0, 0x0c, 0x58, 0x9c, 0x48, 0x1e, 0xec, 0xc3, 0x74, 0x32, 0xe1, 0xfd, 0x41,
	0x08, 0xe7, 0xbf, 0xf3, 0x90, 0x43, 0x3b, 0x92, 0x49, 0xf4, 0xcf, 0x07, 0x68, 0x24, 0x91, 0x1c,
	0xdd, 0x3f, 0xf0, 0x56, 0xda, 0xf0, 0x43, 0xef, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x82, 0xbd,
	0xae, 0xd7, 0x80, 0x01, 0x00, 0x00,
}
