// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: proto/tpm.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum values come from TCG Algorithm Registry - v1.27 - Table 3
type ObjectType int32

const (
	ObjectType_OBJECT_INVALID ObjectType = 0
	ObjectType_RSA            ObjectType = 1
	ObjectType_ECC            ObjectType = 35
)

// Enum value maps for ObjectType.
var (
	ObjectType_name = map[int32]string{
		0:  "OBJECT_INVALID",
		1:  "RSA",
		35: "ECC",
	}
	ObjectType_value = map[string]int32{
		"OBJECT_INVALID": 0,
		"RSA":            1,
		"ECC":            35,
	}
)

func (x ObjectType) Enum() *ObjectType {
	p := new(ObjectType)
	*p = x
	return p
}

func (x ObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tpm_proto_enumTypes[0].Descriptor()
}

func (ObjectType) Type() protoreflect.EnumType {
	return &file_proto_tpm_proto_enumTypes[0]
}

func (x ObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectType.Descriptor instead.
func (ObjectType) EnumDescriptor() ([]byte, []int) {
	return file_proto_tpm_proto_rawDescGZIP(), []int{0}
}

type HashAlgo int32

const (
	HashAlgo_HASH_INVALID HashAlgo = 0
	HashAlgo_SHA1         HashAlgo = 4
	HashAlgo_SHA256       HashAlgo = 11
)

// Enum value maps for HashAlgo.
var (
	HashAlgo_name = map[int32]string{
		0:  "HASH_INVALID",
		4:  "SHA1",
		11: "SHA256",
	}
	HashAlgo_value = map[string]int32{
		"HASH_INVALID": 0,
		"SHA1":         4,
		"SHA256":       11,
	}
)

func (x HashAlgo) Enum() *HashAlgo {
	p := new(HashAlgo)
	*p = x
	return p
}

func (x HashAlgo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HashAlgo) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tpm_proto_enumTypes[1].Descriptor()
}

func (HashAlgo) Type() protoreflect.EnumType {
	return &file_proto_tpm_proto_enumTypes[1]
}

func (x HashAlgo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HashAlgo.Descriptor instead.
func (HashAlgo) EnumDescriptor() ([]byte, []int) {
	return file_proto_tpm_proto_rawDescGZIP(), []int{1}
}

// SealedBytes stores the result of a TPM2_Seal. The private portion (priv) has
// already been encrypted and is no longer sensitive. The hash algorithm is
// assumed to be SHA256.
type SealedBytes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Priv          []byte     `protobuf:"bytes,1,opt,name=priv,proto3" json:"priv,omitempty"`
	Pub           []byte     `protobuf:"bytes,2,opt,name=pub,proto3" json:"pub,omitempty"`
	Pcrs          []int32    `protobuf:"varint,3,rep,packed,name=pcrs,proto3" json:"pcrs,omitempty"`
	Hash          HashAlgo   `protobuf:"varint,4,opt,name=hash,proto3,enum=HashAlgo" json:"hash,omitempty"`
	Srk           ObjectType `protobuf:"varint,5,opt,name=srk,proto3,enum=ObjectType" json:"srk,omitempty"`
	CertifiedPcrs *Pcrs      `protobuf:"bytes,6,opt,name=certified_pcrs,json=certifiedPcrs,proto3" json:"certified_pcrs,omitempty"`
	CreationData  []byte     `protobuf:"bytes,7,opt,name=creation_data,json=creationData,proto3" json:"creation_data,omitempty"`
	Ticket        []byte     `protobuf:"bytes,8,opt,name=ticket,proto3" json:"ticket,omitempty"`
}

func (x *SealedBytes) Reset() {
	*x = SealedBytes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tpm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SealedBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealedBytes) ProtoMessage() {}

func (x *SealedBytes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tpm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealedBytes.ProtoReflect.Descriptor instead.
func (*SealedBytes) Descriptor() ([]byte, []int) {
	return file_proto_tpm_proto_rawDescGZIP(), []int{0}
}

func (x *SealedBytes) GetPriv() []byte {
	if x != nil {
		return x.Priv
	}
	return nil
}

func (x *SealedBytes) GetPub() []byte {
	if x != nil {
		return x.Pub
	}
	return nil
}

func (x *SealedBytes) GetPcrs() []int32 {
	if x != nil {
		return x.Pcrs
	}
	return nil
}

func (x *SealedBytes) GetHash() HashAlgo {
	if x != nil {
		return x.Hash
	}
	return HashAlgo_HASH_INVALID
}

func (x *SealedBytes) GetSrk() ObjectType {
	if x != nil {
		return x.Srk
	}
	return ObjectType_OBJECT_INVALID
}

func (x *SealedBytes) GetCertifiedPcrs() *Pcrs {
	if x != nil {
		return x.CertifiedPcrs
	}
	return nil
}

func (x *SealedBytes) GetCreationData() []byte {
	if x != nil {
		return x.CreationData
	}
	return nil
}

func (x *SealedBytes) GetTicket() []byte {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type ImportBlob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Duplicate     []byte `protobuf:"bytes,1,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	EncryptedSeed []byte `protobuf:"bytes,2,opt,name=encrypted_seed,json=encryptedSeed,proto3" json:"encrypted_seed,omitempty"`
	PublicArea    []byte `protobuf:"bytes,3,opt,name=public_area,json=publicArea,proto3" json:"public_area,omitempty"`
	Pcrs          *Pcrs  `protobuf:"bytes,4,opt,name=pcrs,proto3" json:"pcrs,omitempty"`
}

func (x *ImportBlob) Reset() {
	*x = ImportBlob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tpm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportBlob) ProtoMessage() {}

func (x *ImportBlob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tpm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportBlob.ProtoReflect.Descriptor instead.
func (*ImportBlob) Descriptor() ([]byte, []int) {
	return file_proto_tpm_proto_rawDescGZIP(), []int{1}
}

func (x *ImportBlob) GetDuplicate() []byte {
	if x != nil {
		return x.Duplicate
	}
	return nil
}

func (x *ImportBlob) GetEncryptedSeed() []byte {
	if x != nil {
		return x.EncryptedSeed
	}
	return nil
}

func (x *ImportBlob) GetPublicArea() []byte {
	if x != nil {
		return x.PublicArea
	}
	return nil
}

func (x *ImportBlob) GetPcrs() *Pcrs {
	if x != nil {
		return x.Pcrs
	}
	return nil
}

type Pcrs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash HashAlgo          `protobuf:"varint,1,opt,name=hash,proto3,enum=HashAlgo" json:"hash,omitempty"`
	Pcrs map[uint32][]byte `protobuf:"bytes,2,rep,name=pcrs,proto3" json:"pcrs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Pcrs) Reset() {
	*x = Pcrs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tpm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pcrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pcrs) ProtoMessage() {}

func (x *Pcrs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tpm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pcrs.ProtoReflect.Descriptor instead.
func (*Pcrs) Descriptor() ([]byte, []int) {
	return file_proto_tpm_proto_rawDescGZIP(), []int{2}
}

func (x *Pcrs) GetHash() HashAlgo {
	if x != nil {
		return x.Hash
	}
	return HashAlgo_HASH_INVALID
}

func (x *Pcrs) GetPcrs() map[uint32][]byte {
	if x != nil {
		return x.Pcrs
	}
	return nil
}

var File_proto_tpm_proto protoreflect.FileDescriptor

var file_proto_tpm_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x70, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xf0, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x6c, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x72, 0x69, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x70, 0x72, 0x69, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x75, 0x62, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x70, 0x75, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x63, 0x72, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x70, 0x63, 0x72, 0x73, 0x12, 0x1d, 0x0a, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x48, 0x61, 0x73, 0x68,
	0x41, 0x6c, 0x67, 0x6f, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x1d, 0x0a, 0x03, 0x73, 0x72,
	0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x03, 0x73, 0x72, 0x6b, 0x12, 0x2c, 0x0a, 0x0e, 0x63, 0x65, 0x72,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x70, 0x63, 0x72, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x05, 0x2e, 0x50, 0x63, 0x72, 0x73, 0x52, 0x0d, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x50, 0x63, 0x72, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x22, 0x8d, 0x01, 0x0a, 0x0a, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x42,
	0x6c, 0x6f, 0x62, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x75, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x64, 0x75, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x5f, 0x73,
	0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x65, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x65, 0x64, 0x53, 0x65, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x5f, 0x61, 0x72, 0x65, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x41, 0x72, 0x65, 0x61, 0x12, 0x19, 0x0a, 0x04, 0x70, 0x63, 0x72,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x50, 0x63, 0x72, 0x73, 0x52, 0x04,
	0x70, 0x63, 0x72, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x04, 0x50, 0x63, 0x72, 0x73, 0x12, 0x1d, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x48, 0x61,
	0x73, 0x68, 0x41, 0x6c, 0x67, 0x6f, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x23, 0x0a, 0x04,
	0x70, 0x63, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x50, 0x63, 0x72,
	0x73, 0x2e, 0x50, 0x63, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x70, 0x63, 0x72,
	0x73, 0x1a, 0x37, 0x0a, 0x09, 0x50, 0x63, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0x32, 0x0a, 0x0a, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x42, 0x4a, 0x45,
	0x43, 0x54, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03,
	0x52, 0x53, 0x41, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x43, 0x43, 0x10, 0x23, 0x2a, 0x32,
	0x0a, 0x08, 0x48, 0x61, 0x73, 0x68, 0x41, 0x6c, 0x67, 0x6f, 0x12, 0x10, 0x0a, 0x0c, 0x48, 0x41,
	0x53, 0x48, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x53, 0x48, 0x41, 0x31, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36,
	0x10, 0x0b, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x70, 0x6d, 0x2d, 0x74,
	0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_tpm_proto_rawDescOnce sync.Once
	file_proto_tpm_proto_rawDescData = file_proto_tpm_proto_rawDesc
)

func file_proto_tpm_proto_rawDescGZIP() []byte {
	file_proto_tpm_proto_rawDescOnce.Do(func() {
		file_proto_tpm_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_tpm_proto_rawDescData)
	})
	return file_proto_tpm_proto_rawDescData
}

var file_proto_tpm_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_tpm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_tpm_proto_goTypes = []interface{}{
	(ObjectType)(0),     // 0: ObjectType
	(HashAlgo)(0),       // 1: HashAlgo
	(*SealedBytes)(nil), // 2: SealedBytes
	(*ImportBlob)(nil),  // 3: ImportBlob
	(*Pcrs)(nil),        // 4: Pcrs
	nil,                 // 5: Pcrs.PcrsEntry
}
var file_proto_tpm_proto_depIdxs = []int32{
	1, // 0: SealedBytes.hash:type_name -> HashAlgo
	0, // 1: SealedBytes.srk:type_name -> ObjectType
	4, // 2: SealedBytes.certified_pcrs:type_name -> Pcrs
	4, // 3: ImportBlob.pcrs:type_name -> Pcrs
	1, // 4: Pcrs.hash:type_name -> HashAlgo
	5, // 5: Pcrs.pcrs:type_name -> Pcrs.PcrsEntry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_tpm_proto_init() }
func file_proto_tpm_proto_init() {
	if File_proto_tpm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_tpm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SealedBytes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tpm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportBlob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tpm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pcrs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_tpm_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_tpm_proto_goTypes,
		DependencyIndexes: file_proto_tpm_proto_depIdxs,
		EnumInfos:         file_proto_tpm_proto_enumTypes,
		MessageInfos:      file_proto_tpm_proto_msgTypes,
	}.Build()
	File_proto_tpm_proto = out.File
	file_proto_tpm_proto_rawDesc = nil
	file_proto_tpm_proto_goTypes = nil
	file_proto_tpm_proto_depIdxs = nil
}
