// Package models contains structs for Confidential VM attestation.
package models

const (
	// WorkloadAttestationLabel is the label used by Confidential Space.
	WorkloadAttestationLabel = "WORKLOAD_ATTESTATION"
)

// VMAttestation represents a standalone attestation over a challenge provided by the workload.
type VMAttestation struct {
	// Label provided by the attesting entity. For Confidential Space, this shall be "WORKLOAD_ATTESTATION".
	Label []byte `json:"label"`

	// Challenge provided by the workload.
	Challenge []byte `json:"challenge"`

	// Optional, provided by WSD.
	ExtraData []byte `json:"extra_data,omitempty"`

	// Quote from the CVM.
	Quote *VMAttestationQuote `json:"vm_attestation_quote"`

	// Attestation reports for attached devices.
	DeviceReports []DeviceAttestationReport `json:"device_reports,omitempty"`
}

// VMAttestationQuote represents a quote from a Confidential VM.
type VMAttestationQuote struct {
	// A TDX with CCEL and RTMR Attestation Quote.
	TDXCCELQuote *TDXCCELQuote `json:"tdx_ccel_quote,omitempty"`

	// TPMQuote represents the standalone vTPM Attestation Quote.
	TPMQuote *TPMQuote `json:"tpm_quote,omitempty"`
}

// TDXCCELQuote represents a TDX attestation with CCEL event logs.
type TDXCCELQuote struct {
	// The CCEL event log. Formatted as described in the UEFI 2.10.
	// Contains events for guest OS boot.
	CCELBootEventLog []byte `json:"ccel_boot_event_log"`

	// Formatted as a Canonical Event Log.
	// The event log containing Attested COS launcher events.
	CELLaunchEventLog []byte `json:"cel_launch_event_log"`

	// The TDX attestation quote.
	TDQuote []byte `json:"td_quote"`
}

// DeviceAttestationReport represents an attestation report from a device.
// TODO: Define this.
type DeviceAttestationReport struct {
}

// TPMAttestationEndorsement represents the endorsement of a TPM attestation.
type TPMAttestationEndorsement struct {
	AKCertEndorsement *AKCertEndorsement `json:"ak_cert_endorsement,omitempty"`
	TitanEndorsement  *TitanEndorsement  `json:"titan_endorsement,omitempty"`
}

// AKCertEndorsement represents an attestation key (AK) certificate and cert chain.
type AKCertEndorsement struct {
	AKCert      []byte   `json:"ak_cert"`
	AKCertChain [][]byte `json:"ak_cert_chain"`
}

// TitanEndorsement represents the endorsement of a Titan chip.
type TitanEndorsement struct {
	// Certificate signed by Titan's DICE alias key over the EK used to generate the
	// quotes. On Titan, the EK is a signing key that can be used directly.
	EKCert []byte `json:"ek_cert"`

	// Certificate signed by Titan's DeviceID public key over the alias key used to
	// endorse the EK.
	AliasCert []byte `json:"alias_cert"`

	// Device ID certificate for the Titan chip.
	DeviceIDCert []byte `json:"device_id_cert"`
}

// TPMQuote represents a TPM Quote.
type TPMQuote struct {
	// Generated by calling TPM2_Quote on each PCR bank.
	Quotes []*SignedQuote `json:"quotes"`

	// The binary TCG Event Log containing events measured into the TPM by the
	// platform firmware and operating system. Formatted as described in the
	// "TCG PC Client Platform Firmware Profile Specification" as a series of
	// TCG_PCR_EVENT2 entries.
	PCClientBootEventLog []byte `json:"pcclient_boot_event_log"`

	// Formatted as a Canonical Event Log.
	// The event log containing Attested COS launcher events.
	CELLaunchEventLog []byte `json:"cel_launch_event_log"`

	// Endorsement for the TPM attestation.
	Endorsement *TPMAttestationEndorsement `json:"endorsement"`
}

// SignedQuote represents a signed TPM quote.
type SignedQuote struct {
	HashAlgorithm uint32            `json:"hash_algorithm"` // Encoded as a TPM_ALG_ID.
	PCRValues     map[uint32][]byte `json:"pcr_values"`     // Raw binary values of each PCR being quoted.
	TPMSAttest    []byte            `json:"tpms_attest"`    // Contains a TPMS_QUOTE_INFO.
	TPMTSignature []byte            `json:"tpmt_signature"` // Contains the signature.
}
