// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: workload_service/proto/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KemAlgorithm int32

const (
	KemAlgorithm_KEM_ALGORITHM_UNSPECIFIED KemAlgorithm = 0
	KemAlgorithm_DHKEM_X25519_HKDF_SHA256  KemAlgorithm = 1
)

// Enum value maps for KemAlgorithm.
var (
	KemAlgorithm_name = map[int32]string{
		0: "KEM_ALGORITHM_UNSPECIFIED",
		1: "DHKEM_X25519_HKDF_SHA256",
	}
	KemAlgorithm_value = map[string]int32{
		"KEM_ALGORITHM_UNSPECIFIED": 0,
		"DHKEM_X25519_HKDF_SHA256":  1,
	}
)

func (x KemAlgorithm) Enum() *KemAlgorithm {
	p := new(KemAlgorithm)
	*p = x
	return p
}

func (x KemAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KemAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_workload_service_proto_api_proto_enumTypes[0].Descriptor()
}

func (KemAlgorithm) Type() protoreflect.EnumType {
	return &file_workload_service_proto_api_proto_enumTypes[0]
}

func (x KemAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KemAlgorithm.Descriptor instead.
func (KemAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{0}
}

type KeyHandle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyHandle) Reset() {
	*x = KeyHandle{}
	mi := &file_workload_service_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyHandle) ProtoMessage() {}

func (x *KeyHandle) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyHandle.ProtoReflect.Descriptor instead.
func (*KeyHandle) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *KeyHandle) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type AlgorithmParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KemId         KemAlgorithm           `protobuf:"varint,1,opt,name=kem_id,json=kemId,proto3,enum=keymanager.workload_service.KemAlgorithm" json:"kem_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlgorithmParams) Reset() {
	*x = AlgorithmParams{}
	mi := &file_workload_service_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlgorithmParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlgorithmParams) ProtoMessage() {}

func (x *AlgorithmParams) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlgorithmParams.ProtoReflect.Descriptor instead.
func (*AlgorithmParams) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *AlgorithmParams) GetKemId() KemAlgorithm {
	if x != nil {
		return x.KemId
	}
	return KemAlgorithm_KEM_ALGORITHM_UNSPECIFIED
}

type AlgorithmDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Params        *AlgorithmParams       `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlgorithmDetails) Reset() {
	*x = AlgorithmDetails{}
	mi := &file_workload_service_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlgorithmDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlgorithmDetails) ProtoMessage() {}

func (x *AlgorithmDetails) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlgorithmDetails.ProtoReflect.Descriptor instead.
func (*AlgorithmDetails) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *AlgorithmDetails) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AlgorithmDetails) GetParams() *AlgorithmParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type SupportedAlgorithm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     *AlgorithmDetails      `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportedAlgorithm) Reset() {
	*x = SupportedAlgorithm{}
	mi := &file_workload_service_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportedAlgorithm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedAlgorithm) ProtoMessage() {}

func (x *SupportedAlgorithm) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedAlgorithm.ProtoReflect.Descriptor instead.
func (*SupportedAlgorithm) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *SupportedAlgorithm) GetAlgorithm() *AlgorithmDetails {
	if x != nil {
		return x.Algorithm
	}
	return nil
}

type GetCapabilitiesResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SupportedAlgorithms []*SupportedAlgorithm  `protobuf:"bytes,1,rep,name=supported_algorithms,json=supportedAlgorithms,proto3" json:"supported_algorithms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_workload_service_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetCapabilitiesResponse) GetSupportedAlgorithms() []*SupportedAlgorithm {
	if x != nil {
		return x.SupportedAlgorithms
	}
	return nil
}

type GenerateKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     *AlgorithmDetails      `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Lifespan      uint64                 `protobuf:"varint,2,opt,name=lifespan,proto3" json:"lifespan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKeyRequest) Reset() {
	*x = GenerateKeyRequest{}
	mi := &file_workload_service_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyRequest) ProtoMessage() {}

func (x *GenerateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyRequest.ProtoReflect.Descriptor instead.
func (*GenerateKeyRequest) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateKeyRequest) GetAlgorithm() *AlgorithmDetails {
	if x != nil {
		return x.Algorithm
	}
	return nil
}

func (x *GenerateKeyRequest) GetLifespan() uint64 {
	if x != nil {
		return x.Lifespan
	}
	return 0
}

type PubKeyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     *AlgorithmDetails      `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubKeyInfo) Reset() {
	*x = PubKeyInfo{}
	mi := &file_workload_service_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubKeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubKeyInfo) ProtoMessage() {}

func (x *PubKeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubKeyInfo.ProtoReflect.Descriptor instead.
func (*PubKeyInfo) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *PubKeyInfo) GetAlgorithm() *AlgorithmDetails {
	if x != nil {
		return x.Algorithm
	}
	return nil
}

func (x *PubKeyInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type GenerateKeyResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	KeyHandle              *KeyHandle             `protobuf:"bytes,1,opt,name=key_handle,json=keyHandle,proto3" json:"key_handle,omitempty"`
	PubKey                 *PubKeyInfo            `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	KeyProtectionMechanism string                 `protobuf:"bytes,3,opt,name=key_protection_mechanism,json=keyProtectionMechanism,proto3" json:"key_protection_mechanism,omitempty"`
	ExpirationTime         float64                `protobuf:"fixed64,4,opt,name=expiration_time,json=expirationTime,proto3" json:"expiration_time,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GenerateKeyResponse) Reset() {
	*x = GenerateKeyResponse{}
	mi := &file_workload_service_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyResponse) ProtoMessage() {}

func (x *GenerateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyResponse.ProtoReflect.Descriptor instead.
func (*GenerateKeyResponse) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateKeyResponse) GetKeyHandle() *KeyHandle {
	if x != nil {
		return x.KeyHandle
	}
	return nil
}

func (x *GenerateKeyResponse) GetPubKey() *PubKeyInfo {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *GenerateKeyResponse) GetKeyProtectionMechanism() string {
	if x != nil {
		return x.KeyProtectionMechanism
	}
	return ""
}

func (x *GenerateKeyResponse) GetExpirationTime() float64 {
	if x != nil {
		return x.ExpirationTime
	}
	return 0
}

type KeyInfo struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	KeyHandle              *KeyHandle             `protobuf:"bytes,1,opt,name=key_handle,json=keyHandle,proto3" json:"key_handle,omitempty"`
	PubKey                 *PubKeyInfo            `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	KeyProtectionMechanism string                 `protobuf:"bytes,3,opt,name=key_protection_mechanism,json=keyProtectionMechanism,proto3" json:"key_protection_mechanism,omitempty"`
	ExpirationTime         float64                `protobuf:"fixed64,4,opt,name=expiration_time,json=expirationTime,proto3" json:"expiration_time,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *KeyInfo) Reset() {
	*x = KeyInfo{}
	mi := &file_workload_service_proto_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyInfo) ProtoMessage() {}

func (x *KeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyInfo.ProtoReflect.Descriptor instead.
func (*KeyInfo) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{8}
}

func (x *KeyInfo) GetKeyHandle() *KeyHandle {
	if x != nil {
		return x.KeyHandle
	}
	return nil
}

func (x *KeyInfo) GetPubKey() *PubKeyInfo {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *KeyInfo) GetKeyProtectionMechanism() string {
	if x != nil {
		return x.KeyProtectionMechanism
	}
	return ""
}

func (x *KeyInfo) GetExpirationTime() float64 {
	if x != nil {
		return x.ExpirationTime
	}
	return 0
}

type EnumerateKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyInfos      []*KeyInfo             `protobuf:"bytes,1,rep,name=key_infos,json=keyInfos,proto3" json:"key_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateKeysResponse) Reset() {
	*x = EnumerateKeysResponse{}
	mi := &file_workload_service_proto_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateKeysResponse) ProtoMessage() {}

func (x *EnumerateKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateKeysResponse.ProtoReflect.Descriptor instead.
func (*EnumerateKeysResponse) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *EnumerateKeysResponse) GetKeyInfos() []*KeyInfo {
	if x != nil {
		return x.KeyInfos
	}
	return nil
}

type KemCiphertext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     KemAlgorithm           `protobuf:"varint,1,opt,name=algorithm,proto3,enum=keymanager.workload_service.KemAlgorithm" json:"algorithm,omitempty"`
	Ciphertext    string                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KemCiphertext) Reset() {
	*x = KemCiphertext{}
	mi := &file_workload_service_proto_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KemCiphertext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KemCiphertext) ProtoMessage() {}

func (x *KemCiphertext) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KemCiphertext.ProtoReflect.Descriptor instead.
func (*KemCiphertext) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *KemCiphertext) GetAlgorithm() KemAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return KemAlgorithm_KEM_ALGORITHM_UNSPECIFIED
}

func (x *KemCiphertext) GetCiphertext() string {
	if x != nil {
		return x.Ciphertext
	}
	return ""
}

type DecapsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyHandle     *KeyHandle             `protobuf:"bytes,1,opt,name=key_handle,json=keyHandle,proto3" json:"key_handle,omitempty"`
	Ciphertext    *KemCiphertext         `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecapsRequest) Reset() {
	*x = DecapsRequest{}
	mi := &file_workload_service_proto_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecapsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecapsRequest) ProtoMessage() {}

func (x *DecapsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecapsRequest.ProtoReflect.Descriptor instead.
func (*DecapsRequest) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{11}
}

func (x *DecapsRequest) GetKeyHandle() *KeyHandle {
	if x != nil {
		return x.KeyHandle
	}
	return nil
}

func (x *DecapsRequest) GetCiphertext() *KemCiphertext {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type KemSharedSecret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     KemAlgorithm           `protobuf:"varint,1,opt,name=algorithm,proto3,enum=keymanager.workload_service.KemAlgorithm" json:"algorithm,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KemSharedSecret) Reset() {
	*x = KemSharedSecret{}
	mi := &file_workload_service_proto_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KemSharedSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KemSharedSecret) ProtoMessage() {}

func (x *KemSharedSecret) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KemSharedSecret.ProtoReflect.Descriptor instead.
func (*KemSharedSecret) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{12}
}

func (x *KemSharedSecret) GetAlgorithm() KemAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return KemAlgorithm_KEM_ALGORITHM_UNSPECIFIED
}

func (x *KemSharedSecret) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type DecapsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SharedSecret  *KemSharedSecret       `protobuf:"bytes,1,opt,name=shared_secret,json=sharedSecret,proto3" json:"shared_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecapsResponse) Reset() {
	*x = DecapsResponse{}
	mi := &file_workload_service_proto_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecapsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecapsResponse) ProtoMessage() {}

func (x *DecapsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecapsResponse.ProtoReflect.Descriptor instead.
func (*DecapsResponse) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{13}
}

func (x *DecapsResponse) GetSharedSecret() *KemSharedSecret {
	if x != nil {
		return x.SharedSecret
	}
	return nil
}

type DestroyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyHandle     *KeyHandle             `protobuf:"bytes,1,opt,name=key_handle,json=keyHandle,proto3" json:"key_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	mi := &file_workload_service_proto_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{14}
}

func (x *DestroyRequest) GetKeyHandle() *KeyHandle {
	if x != nil {
		return x.KeyHandle
	}
	return nil
}

var File_workload_service_proto_api_proto protoreflect.FileDescriptor

const file_workload_service_proto_api_proto_rawDesc = "" +
	"\n" +
	" workload_service/proto/api.proto\x12\x1bkeymanager.workload_service\"#\n" +
	"\tKeyHandle\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\"S\n" +
	"\x0fAlgorithmParams\x12@\n" +
	"\x06kem_id\x18\x01 \x01(\x0e2).keymanager.workload_service.KemAlgorithmR\x05kemId\"l\n" +
	"\x10AlgorithmDetails\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12D\n" +
	"\x06params\x18\x02 \x01(\v2,.keymanager.workload_service.AlgorithmParamsR\x06params\"a\n" +
	"\x12SupportedAlgorithm\x12K\n" +
	"\talgorithm\x18\x01 \x01(\v2-.keymanager.workload_service.AlgorithmDetailsR\talgorithm\"}\n" +
	"\x17GetCapabilitiesResponse\x12b\n" +
	"\x14supported_algorithms\x18\x01 \x03(\v2/.keymanager.workload_service.SupportedAlgorithmR\x13supportedAlgorithms\"}\n" +
	"\x12GenerateKeyRequest\x12K\n" +
	"\talgorithm\x18\x01 \x01(\v2-.keymanager.workload_service.AlgorithmDetailsR\talgorithm\x12\x1a\n" +
	"\blifespan\x18\x02 \x01(\x04R\blifespan\"x\n" +
	"\n" +
	"PubKeyInfo\x12K\n" +
	"\talgorithm\x18\x01 \x01(\v2-.keymanager.workload_service.AlgorithmDetailsR\talgorithm\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\"\x81\x02\n" +
	"\x13GenerateKeyResponse\x12E\n" +
	"\n" +
	"key_handle\x18\x01 \x01(\v2&.keymanager.workload_service.KeyHandleR\tkeyHandle\x12@\n" +
	"\apub_key\x18\x02 \x01(\v2'.keymanager.workload_service.PubKeyInfoR\x06pubKey\x128\n" +
	"\x18key_protection_mechanism\x18\x03 \x01(\tR\x16keyProtectionMechanism\x12'\n" +
	"\x0fexpiration_time\x18\x04 \x01(\x01R\x0eexpirationTime\"\xf5\x01\n" +
	"\aKeyInfo\x12E\n" +
	"\n" +
	"key_handle\x18\x01 \x01(\v2&.keymanager.workload_service.KeyHandleR\tkeyHandle\x12@\n" +
	"\apub_key\x18\x02 \x01(\v2'.keymanager.workload_service.PubKeyInfoR\x06pubKey\x128\n" +
	"\x18key_protection_mechanism\x18\x03 \x01(\tR\x16keyProtectionMechanism\x12'\n" +
	"\x0fexpiration_time\x18\x04 \x01(\x01R\x0eexpirationTime\"Z\n" +
	"\x15EnumerateKeysResponse\x12A\n" +
	"\tkey_infos\x18\x01 \x03(\v2$.keymanager.workload_service.KeyInfoR\bkeyInfos\"x\n" +
	"\rKemCiphertext\x12G\n" +
	"\talgorithm\x18\x01 \x01(\x0e2).keymanager.workload_service.KemAlgorithmR\talgorithm\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\tR\n" +
	"ciphertext\"\xa2\x01\n" +
	"\rDecapsRequest\x12E\n" +
	"\n" +
	"key_handle\x18\x01 \x01(\v2&.keymanager.workload_service.KeyHandleR\tkeyHandle\x12J\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\v2*.keymanager.workload_service.KemCiphertextR\n" +
	"ciphertext\"r\n" +
	"\x0fKemSharedSecret\x12G\n" +
	"\talgorithm\x18\x01 \x01(\x0e2).keymanager.workload_service.KemAlgorithmR\talgorithm\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"c\n" +
	"\x0eDecapsResponse\x12Q\n" +
	"\rshared_secret\x18\x01 \x01(\v2,.keymanager.workload_service.KemSharedSecretR\fsharedSecret\"W\n" +
	"\x0eDestroyRequest\x12E\n" +
	"\n" +
	"key_handle\x18\x01 \x01(\v2&.keymanager.workload_service.KeyHandleR\tkeyHandle*K\n" +
	"\fKemAlgorithm\x12\x1d\n" +
	"\x19KEM_ALGORITHM_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DHKEM_X25519_HKDF_SHA256\x10\x01BFZDgithub.com/google/go-tpm-tools/keymanager/workload_service/proto;apib\x06proto3"

var (
	file_workload_service_proto_api_proto_rawDescOnce sync.Once
	file_workload_service_proto_api_proto_rawDescData []byte
)

func file_workload_service_proto_api_proto_rawDescGZIP() []byte {
	file_workload_service_proto_api_proto_rawDescOnce.Do(func() {
		file_workload_service_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workload_service_proto_api_proto_rawDesc), len(file_workload_service_proto_api_proto_rawDesc)))
	})
	return file_workload_service_proto_api_proto_rawDescData
}

var file_workload_service_proto_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_workload_service_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_workload_service_proto_api_proto_goTypes = []any{
	(KemAlgorithm)(0),               // 0: keymanager.workload_service.KemAlgorithm
	(*KeyHandle)(nil),               // 1: keymanager.workload_service.KeyHandle
	(*AlgorithmParams)(nil),         // 2: keymanager.workload_service.AlgorithmParams
	(*AlgorithmDetails)(nil),        // 3: keymanager.workload_service.AlgorithmDetails
	(*SupportedAlgorithm)(nil),      // 4: keymanager.workload_service.SupportedAlgorithm
	(*GetCapabilitiesResponse)(nil), // 5: keymanager.workload_service.GetCapabilitiesResponse
	(*GenerateKeyRequest)(nil),      // 6: keymanager.workload_service.GenerateKeyRequest
	(*PubKeyInfo)(nil),              // 7: keymanager.workload_service.PubKeyInfo
	(*GenerateKeyResponse)(nil),     // 8: keymanager.workload_service.GenerateKeyResponse
	(*KeyInfo)(nil),                 // 9: keymanager.workload_service.KeyInfo
	(*EnumerateKeysResponse)(nil),   // 10: keymanager.workload_service.EnumerateKeysResponse
	(*KemCiphertext)(nil),           // 11: keymanager.workload_service.KemCiphertext
	(*DecapsRequest)(nil),           // 12: keymanager.workload_service.DecapsRequest
	(*KemSharedSecret)(nil),         // 13: keymanager.workload_service.KemSharedSecret
	(*DecapsResponse)(nil),          // 14: keymanager.workload_service.DecapsResponse
	(*DestroyRequest)(nil),          // 15: keymanager.workload_service.DestroyRequest
}
var file_workload_service_proto_api_proto_depIdxs = []int32{
	0,  // 0: keymanager.workload_service.AlgorithmParams.kem_id:type_name -> keymanager.workload_service.KemAlgorithm
	2,  // 1: keymanager.workload_service.AlgorithmDetails.params:type_name -> keymanager.workload_service.AlgorithmParams
	3,  // 2: keymanager.workload_service.SupportedAlgorithm.algorithm:type_name -> keymanager.workload_service.AlgorithmDetails
	4,  // 3: keymanager.workload_service.GetCapabilitiesResponse.supported_algorithms:type_name -> keymanager.workload_service.SupportedAlgorithm
	3,  // 4: keymanager.workload_service.GenerateKeyRequest.algorithm:type_name -> keymanager.workload_service.AlgorithmDetails
	3,  // 5: keymanager.workload_service.PubKeyInfo.algorithm:type_name -> keymanager.workload_service.AlgorithmDetails
	1,  // 6: keymanager.workload_service.GenerateKeyResponse.key_handle:type_name -> keymanager.workload_service.KeyHandle
	7,  // 7: keymanager.workload_service.GenerateKeyResponse.pub_key:type_name -> keymanager.workload_service.PubKeyInfo
	1,  // 8: keymanager.workload_service.KeyInfo.key_handle:type_name -> keymanager.workload_service.KeyHandle
	7,  // 9: keymanager.workload_service.KeyInfo.pub_key:type_name -> keymanager.workload_service.PubKeyInfo
	9,  // 10: keymanager.workload_service.EnumerateKeysResponse.key_infos:type_name -> keymanager.workload_service.KeyInfo
	0,  // 11: keymanager.workload_service.KemCiphertext.algorithm:type_name -> keymanager.workload_service.KemAlgorithm
	1,  // 12: keymanager.workload_service.DecapsRequest.key_handle:type_name -> keymanager.workload_service.KeyHandle
	11, // 13: keymanager.workload_service.DecapsRequest.ciphertext:type_name -> keymanager.workload_service.KemCiphertext
	0,  // 14: keymanager.workload_service.KemSharedSecret.algorithm:type_name -> keymanager.workload_service.KemAlgorithm
	13, // 15: keymanager.workload_service.DecapsResponse.shared_secret:type_name -> keymanager.workload_service.KemSharedSecret
	1,  // 16: keymanager.workload_service.DestroyRequest.key_handle:type_name -> keymanager.workload_service.KeyHandle
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_workload_service_proto_api_proto_init() }
func file_workload_service_proto_api_proto_init() {
	if File_workload_service_proto_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workload_service_proto_api_proto_rawDesc), len(file_workload_service_proto_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workload_service_proto_api_proto_goTypes,
		DependencyIndexes: file_workload_service_proto_api_proto_depIdxs,
		EnumInfos:         file_workload_service_proto_api_proto_enumTypes,
		MessageInfos:      file_workload_service_proto_api_proto_msgTypes,
	}.Build()
	File_workload_service_proto_api_proto = out.File
	file_workload_service_proto_api_proto_goTypes = nil
	file_workload_service_proto_api_proto_depIdxs = nil
}
