// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workload_service/proto/api.proto

// API definitions for the Workload Services Daemon (WSD)

package api

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	proto "github.com/google/go-tpm-tools/keymanager/km_common/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Response containing the list of supported cryptographic algorithms for operations like HPKE/KEM.
type GetCapabilitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of supported algorithms (e.g., KEM algorithms).
	SupportedAlgorithms []*proto.SupportedAlgorithm `protobuf:"bytes,1,rep,name=supported_algorithms,json=supportedAlgorithms,proto3" json:"supported_algorithms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_workload_service_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetCapabilitiesResponse) GetSupportedAlgorithms() []*proto.SupportedAlgorithm {
	if x != nil {
		return x.SupportedAlgorithms
	}
	return nil
}

// Request to orchestrate the creation of a new keypair (e.g., a KEM keypair). (POST /v1/keys:generate_key)
type GenerateKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The specific algorithm to use for the new keypair.
	Algorithm *proto.AlgorithmDetails `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// The requested duration (in seconds) before the key is automatically destroyed.
	Lifespan      uint64 `protobuf:"varint,2,opt,name=lifespan,proto3" json:"lifespan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKeyRequest) Reset() {
	*x = GenerateKeyRequest{}
	mi := &file_workload_service_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyRequest) ProtoMessage() {}

func (x *GenerateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyRequest.ProtoReflect.Descriptor instead.
func (*GenerateKeyRequest) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateKeyRequest) GetAlgorithm() *proto.AlgorithmDetails {
	if x != nil {
		return x.Algorithm
	}
	return nil
}

func (x *GenerateKeyRequest) GetLifespan() uint64 {
	if x != nil {
		return x.Lifespan
	}
	return 0
}

// Response from generating a new key.
type GenerateKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique handle (UUID) used to reference the generated key.
	KeyHandle *proto.KeyHandle `protobuf:"bytes,1,opt,name=key_handle,json=keyHandle,proto3" json:"key_handle,omitempty"`
	// The public key information for the generated keypair.
	PubKey *proto.PubKeyInfo `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	// The isolation level/protection mechanism for the key
	// (e.g., "KEY_PROTECTION_VM_EMULATED", "KEY_PROTECTION_VM", or "DEFAULT").
	KeyProtectionMechanism string `protobuf:"bytes,3,opt,name=key_protection_mechanism,json=keyProtectionMechanism,proto3" json:"key_protection_mechanism,omitempty"`
	// A Unix timestamp indicating when the key is scheduled for automatic deletion.
	// Note: relies on network clock time and is subject to hypervisor clock drift/skew.
	ExpirationTime float64 `protobuf:"fixed64,4,opt,name=expiration_time,json=expirationTime,proto3" json:"expiration_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateKeyResponse) Reset() {
	*x = GenerateKeyResponse{}
	mi := &file_workload_service_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyResponse) ProtoMessage() {}

func (x *GenerateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyResponse.ProtoReflect.Descriptor instead.
func (*GenerateKeyResponse) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateKeyResponse) GetKeyHandle() *proto.KeyHandle {
	if x != nil {
		return x.KeyHandle
	}
	return nil
}

func (x *GenerateKeyResponse) GetPubKey() *proto.PubKeyInfo {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *GenerateKeyResponse) GetKeyProtectionMechanism() string {
	if x != nil {
		return x.KeyProtectionMechanism
	}
	return ""
}

func (x *GenerateKeyResponse) GetExpirationTime() float64 {
	if x != nil {
		return x.ExpirationTime
	}
	return 0
}

// Detailed information about an active key.
type KeyInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique handle (UUID) used to reference the keypair.
	KeyHandle *proto.KeyHandle `protobuf:"bytes,1,opt,name=key_handle,json=keyHandle,proto3" json:"key_handle,omitempty"`
	// The public key information for the keypair.
	PubKey *proto.PubKeyInfo `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	// The isolation level/protection mechanism for the key.
	KeyProtectionMechanism string `protobuf:"bytes,3,opt,name=key_protection_mechanism,json=keyProtectionMechanism,proto3" json:"key_protection_mechanism,omitempty"`
	// A Unix timestamp indicating when the key will be automatically deleted.
	ExpirationTime float64 `protobuf:"fixed64,4,opt,name=expiration_time,json=expirationTime,proto3" json:"expiration_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeyInfo) Reset() {
	*x = KeyInfo{}
	mi := &file_workload_service_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyInfo) ProtoMessage() {}

func (x *KeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyInfo.ProtoReflect.Descriptor instead.
func (*KeyInfo) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *KeyInfo) GetKeyHandle() *proto.KeyHandle {
	if x != nil {
		return x.KeyHandle
	}
	return nil
}

func (x *KeyInfo) GetPubKey() *proto.PubKeyInfo {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *KeyInfo) GetKeyProtectionMechanism() string {
	if x != nil {
		return x.KeyProtectionMechanism
	}
	return ""
}

func (x *KeyInfo) GetExpirationTime() float64 {
	if x != nil {
		return x.ExpirationTime
	}
	return 0
}

// Response containing a list of all active keys managed by the daemon.
type EnumerateKeysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of active keys along with their metadata.
	KeyInfos      []*KeyInfo `protobuf:"bytes,1,rep,name=key_infos,json=keyInfos,proto3" json:"key_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateKeysResponse) Reset() {
	*x = EnumerateKeysResponse{}
	mi := &file_workload_service_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateKeysResponse) ProtoMessage() {}

func (x *EnumerateKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateKeysResponse.ProtoReflect.Descriptor instead.
func (*EnumerateKeysResponse) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *EnumerateKeysResponse) GetKeyInfos() []*KeyInfo {
	if x != nil {
		return x.KeyInfos
	}
	return nil
}

// Request to perform a decapsulation operation using a specific key handle. (POST /v1/keys:decap)
type DecapsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The handle (UUID) of the KEM key instance to use for decapsulation.
	KeyHandle *proto.KeyHandle `protobuf:"bytes,1,opt,name=key_handle,json=keyHandle,proto3" json:"key_handle,omitempty"`
	// The encapsulated shared secret received from the client/proxy.
	Ciphertext    *proto.KemCiphertext `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecapsRequest) Reset() {
	*x = DecapsRequest{}
	mi := &file_workload_service_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecapsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecapsRequest) ProtoMessage() {}

func (x *DecapsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecapsRequest.ProtoReflect.Descriptor instead.
func (*DecapsRequest) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *DecapsRequest) GetKeyHandle() *proto.KeyHandle {
	if x != nil {
		return x.KeyHandle
	}
	return nil
}

func (x *DecapsRequest) GetCiphertext() *proto.KemCiphertext {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

// Response from a decapsulation operation.
type DecapsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The plaintext shared secret derived from the ciphertext.
	SharedSecret  *proto.KemSharedSecret `protobuf:"bytes,1,opt,name=shared_secret,json=sharedSecret,proto3" json:"shared_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecapsResponse) Reset() {
	*x = DecapsResponse{}
	mi := &file_workload_service_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecapsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecapsResponse) ProtoMessage() {}

func (x *DecapsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecapsResponse.ProtoReflect.Descriptor instead.
func (*DecapsResponse) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *DecapsResponse) GetSharedSecret() *proto.KemSharedSecret {
	if x != nil {
		return x.SharedSecret
	}
	return nil
}

// Request to manually trigger the destruction of a keypair before its lifespan expires. (POST /v1/keys:destroy)
type DestroyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The handle (UUID) of the keypair to destroy.
	KeyHandle     *proto.KeyHandle `protobuf:"bytes,1,opt,name=key_handle,json=keyHandle,proto3" json:"key_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	mi := &file_workload_service_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workload_service_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_workload_service_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *DestroyRequest) GetKeyHandle() *proto.KeyHandle {
	if x != nil {
		return x.KeyHandle
	}
	return nil
}

var File_workload_service_proto_api_proto protoreflect.FileDescriptor

const file_workload_service_proto_api_proto_rawDesc = "" +
	"\n" +
	" workload_service/proto/api.proto\x12\x1bkeymanager.workload_service\x1a km_common/proto/algorithms.proto\x1a\"km_common/proto/crypto_types.proto\x1a\x1dkm_common/proto/payload.proto\x1a\x1bbuf/validate/validate.proto\"l\n" +
	"\x17GetCapabilitiesResponse\x12Q\n" +
	"\x14supported_algorithms\x18\x01 \x03(\v2\x1e.keymanager.SupportedAlgorithmR\x13supportedAlgorithms\"\x87\x01\n" +
	"\x12GenerateKeyRequest\x12B\n" +
	"\talgorithm\x18\x01 \x01(\v2\x1c.keymanager.AlgorithmDetailsB\x06\xbaH\x03\xc8\x01\x01R\talgorithm\x12-\n" +
	"\blifespan\x18\x02 \x01(\x04B\x11\xbaH\x0e2\f\x18\xff\xff\xff\xff\xff\xff\xff\xff\x7f \x00R\blifespan\"\xe7\x01\n" +
	"\x13GenerateKeyResponse\x12<\n" +
	"\n" +
	"key_handle\x18\x01 \x01(\v2\x15.keymanager.KeyHandleB\x06\xbaH\x03\xc8\x01\x01R\tkeyHandle\x12/\n" +
	"\apub_key\x18\x02 \x01(\v2\x16.keymanager.PubKeyInfoR\x06pubKey\x128\n" +
	"\x18key_protection_mechanism\x18\x03 \x01(\tR\x16keyProtectionMechanism\x12'\n" +
	"\x0fexpiration_time\x18\x04 \x01(\x01R\x0eexpirationTime\"\xdb\x01\n" +
	"\aKeyInfo\x12<\n" +
	"\n" +
	"key_handle\x18\x01 \x01(\v2\x15.keymanager.KeyHandleB\x06\xbaH\x03\xc8\x01\x01R\tkeyHandle\x12/\n" +
	"\apub_key\x18\x02 \x01(\v2\x16.keymanager.PubKeyInfoR\x06pubKey\x128\n" +
	"\x18key_protection_mechanism\x18\x03 \x01(\tR\x16keyProtectionMechanism\x12'\n" +
	"\x0fexpiration_time\x18\x04 \x01(\x01R\x0eexpirationTime\"Z\n" +
	"\x15EnumerateKeysResponse\x12A\n" +
	"\tkey_infos\x18\x01 \x03(\v2$.keymanager.workload_service.KeyInfoR\bkeyInfos\"\x90\x01\n" +
	"\rDecapsRequest\x12<\n" +
	"\n" +
	"key_handle\x18\x01 \x01(\v2\x15.keymanager.KeyHandleB\x06\xbaH\x03\xc8\x01\x01R\tkeyHandle\x12A\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\v2\x19.keymanager.KemCiphertextB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"ciphertext\"R\n" +
	"\x0eDecapsResponse\x12@\n" +
	"\rshared_secret\x18\x01 \x01(\v2\x1b.keymanager.KemSharedSecretR\fsharedSecret\"N\n" +
	"\x0eDestroyRequest\x12<\n" +
	"\n" +
	"key_handle\x18\x01 \x01(\v2\x15.keymanager.KeyHandleB\x06\xbaH\x03\xc8\x01\x01R\tkeyHandleBFZDgithub.com/google/go-tpm-tools/keymanager/workload_service/proto;apib\x06proto3"

var (
	file_workload_service_proto_api_proto_rawDescOnce sync.Once
	file_workload_service_proto_api_proto_rawDescData []byte
)

func file_workload_service_proto_api_proto_rawDescGZIP() []byte {
	file_workload_service_proto_api_proto_rawDescOnce.Do(func() {
		file_workload_service_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workload_service_proto_api_proto_rawDesc), len(file_workload_service_proto_api_proto_rawDesc)))
	})
	return file_workload_service_proto_api_proto_rawDescData
}

var file_workload_service_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_workload_service_proto_api_proto_goTypes = []any{
	(*GetCapabilitiesResponse)(nil),  // 0: keymanager.workload_service.GetCapabilitiesResponse
	(*GenerateKeyRequest)(nil),       // 1: keymanager.workload_service.GenerateKeyRequest
	(*GenerateKeyResponse)(nil),      // 2: keymanager.workload_service.GenerateKeyResponse
	(*KeyInfo)(nil),                  // 3: keymanager.workload_service.KeyInfo
	(*EnumerateKeysResponse)(nil),    // 4: keymanager.workload_service.EnumerateKeysResponse
	(*DecapsRequest)(nil),            // 5: keymanager.workload_service.DecapsRequest
	(*DecapsResponse)(nil),           // 6: keymanager.workload_service.DecapsResponse
	(*DestroyRequest)(nil),           // 7: keymanager.workload_service.DestroyRequest
	(*proto.SupportedAlgorithm)(nil), // 8: keymanager.SupportedAlgorithm
	(*proto.AlgorithmDetails)(nil),   // 9: keymanager.AlgorithmDetails
	(*proto.KeyHandle)(nil),          // 10: keymanager.KeyHandle
	(*proto.PubKeyInfo)(nil),         // 11: keymanager.PubKeyInfo
	(*proto.KemCiphertext)(nil),      // 12: keymanager.KemCiphertext
	(*proto.KemSharedSecret)(nil),    // 13: keymanager.KemSharedSecret
}
var file_workload_service_proto_api_proto_depIdxs = []int32{
	8,  // 0: keymanager.workload_service.GetCapabilitiesResponse.supported_algorithms:type_name -> keymanager.SupportedAlgorithm
	9,  // 1: keymanager.workload_service.GenerateKeyRequest.algorithm:type_name -> keymanager.AlgorithmDetails
	10, // 2: keymanager.workload_service.GenerateKeyResponse.key_handle:type_name -> keymanager.KeyHandle
	11, // 3: keymanager.workload_service.GenerateKeyResponse.pub_key:type_name -> keymanager.PubKeyInfo
	10, // 4: keymanager.workload_service.KeyInfo.key_handle:type_name -> keymanager.KeyHandle
	11, // 5: keymanager.workload_service.KeyInfo.pub_key:type_name -> keymanager.PubKeyInfo
	3,  // 6: keymanager.workload_service.EnumerateKeysResponse.key_infos:type_name -> keymanager.workload_service.KeyInfo
	10, // 7: keymanager.workload_service.DecapsRequest.key_handle:type_name -> keymanager.KeyHandle
	12, // 8: keymanager.workload_service.DecapsRequest.ciphertext:type_name -> keymanager.KemCiphertext
	13, // 9: keymanager.workload_service.DecapsResponse.shared_secret:type_name -> keymanager.KemSharedSecret
	10, // 10: keymanager.workload_service.DestroyRequest.key_handle:type_name -> keymanager.KeyHandle
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_workload_service_proto_api_proto_init() }
func file_workload_service_proto_api_proto_init() {
	if File_workload_service_proto_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workload_service_proto_api_proto_rawDesc), len(file_workload_service_proto_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workload_service_proto_api_proto_goTypes,
		DependencyIndexes: file_workload_service_proto_api_proto_depIdxs,
		MessageInfos:      file_workload_service_proto_api_proto_msgTypes,
	}.Build()
	File_workload_service_proto_api_proto = out.File
	file_workload_service_proto_api_proto_goTypes = nil
	file_workload_service_proto_api_proto_depIdxs = nil
}
