steps:
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'DOCKER_BUILDKIT=1'
    args: [
      'buildx', 'build',
      '--build-arg', 'SOURCE_DATE_EPOCH=0',
      '--output', 'type=image,name=us-docker.pkg.dev/${PROJECT_ID}/cs-tools/keymanager-builder:latest,rewrite-timestamp=true,push=true',
      '.'
    ]

options:
  requestedVerifyOption: VERIFIED
