substitutions:
  '_BASE_IMAGE': ''
  '_BASE_IMAGE_PROJECT': ''
  '_BUCKET_NAME': ''
  '_IMAGE_ENV': ''
  '_OUTPUT_IMAGE_NAME': ''
  '_OUTPUT_IMAGE_FAMILY': ''

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'ExportBaseImage'
    args:
      - 'gcloud'
      - 'compute'
      - 'images'
      - 'export'
      - '--image=${_BASE_IMAGE}'
      - '--image-project=${_BASE_IMAGE_PROJECT}'
      - '--destination-uri=gs://${_BUCKET_NAME}/oem-preloader-${BUILD_ID}/${_BASE_IMAGE}.tar.gz'
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'DownloadImageFromGCS'
    entrypoint: 'gcloud'
    args: ['storage',
           'cp',
           'gs://${_BUCKET_NAME}/oem-preloader-${BUILD_ID}/${_BASE_IMAGE}.tar.gz',
           './src_image.tar.gz']
  - name: 'alpine'
    id: 'ExtractRawImage'
    args: ['tar', '-xf', './src_image.tar.gz']

  - name: 'alpine'
    id: 'PrepareOEMInstallDir'
    entrypoint: 'sh'
    args:
      - -c
      - |
        set -eu
        rm -rf /workspace/oem-install
        mkdir -p /workspace/oem-install/confidential_space
        mkdir -p /workspace/oem-install/confidential_space/nodeproblemdetector
        cp ./launcher/image/bc-guest/bcentrypoint.sh /workspace/oem-install/entrypoint.sh
        cp ./launcher/image/bc-guest/bcexperiment.json \
           ./launcher/image/launcher \
           ./launcher/image/container-runner.service \
           ./launcher/image/fluent-bit-cs.conf \
           ./launcher/image/exit_script.sh \
           /workspace/oem-install/confidential_space/
        cp ./launcher/image/nodeproblemdetector/* /workspace/oem-install/confidential_space/nodeproblemdetector/

        cp /workspace/oem-install/confidential_space/launcher /workspace/oem-install/confidential_space/cs_container_launcher
        # Disabled because cloud-init is not used.
        # cp ./launcher/image/bc-guest/meta-data /workspace/oem-install/meta-data
        chmod +x /workspace/oem-install/confidential_space/cs_container_launcher || true
        chmod +x /workspace/oem-install/confidential_space/exit_script.sh || true
        chmod +x /workspace/oem-install/entrypoint.sh || true

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'DownloadVmlinux'
    entrypoint: 'gcloud'
    args: ['storage', 'cp', 'gs://cos-tools/19216.220.185/cchostdebug-amd64-gcp/vmlinux', './vmlinux']
  - name: 'gcr.io/cos-cloud/oem-preloader:latest'
    id: 'RunOEMPreloader'
    env:
      - 'IMAGE_ENV=${_IMAGE_ENV}'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -ex
        COMMON_COMMANDS=(
          # Disabled for cchost base image: Entrypoint is handled directly by systemd, not Cloud-Init.
          # "s|cros_efi|cros_efi ds=nocloud;s=/usr/share/oem/|g"
          "s|cros_efi|cros_efi cos.protected_stateful_partition=m|g"
          "s|cros_efi|cros_efi systemd.default_timeout_start_sec=900s|g"
          "s|cros_efi|cros_efi swiotlb=4194304,force,any|g"
          "s|systemd.mask=usr-share-oem.mount||g"
          "s|dm-m2d|dm-mod|g"
          "s|,oemroot|;oemroot|g"
        )

        DEBUG_COMMANDS=(
          "s|cros_efi|cros_efi systemd.mask=konlet-startup.service|g"
          "s|cros_efi|cros_efi systemd.mask=update-engine.service|g"
          "s|cros_efi|cros_efi confidential-space.hardened=false|g"
        )

        HARDENED_COMMANDS=(
          "s|cros_efi|cros_efi systemd.wants=basic.target|g"
          "s|cros_efi|cros_efi systemd.wants=systemd-resolved.service|g"
          "s|cros_efi|cros_efi systemd.wants=network-online.target|g"
          "s|cros_efi|cros_efi systemd.wants=gcr-online.target|g"
          # Disabled because no cloud-init
          # "s|cros_efi|cros_efi systemd.unit=cloud-final.service|g"
          "s|cros_efi|cros_efi systemd.mask=var-lib-docker.mount|g"
          "s|cros_efi|cros_efi systemd.mask=docker.service|g"
          "s|cros_efi|cros_efi systemd.mask=google-guest-agent.service|g"
          "s|cros_efi|cros_efi systemd.mask=google-osconfig-init.service|g"
          "s|cros_efi|cros_efi systemd.mask=google-osconfig-agent.service|g"
          "s|cros_efi|cros_efi systemd.mask=google-startup-scripts.service|g"
          "s|cros_efi|cros_efi systemd.mask=google-shutdown-scripts.service|g"
          "s|cros_efi|cros_efi systemd.mask=konlet-startup.service|g"
          "s|cros_efi|cros_efi systemd.mask=crash-reporter.service|g"
          "s|cros_efi|cros_efi systemd.mask=device_policy_manager.service|g"
          "s|cros_efi|cros_efi systemd.mask=docker-events-collector-fluent-bit.service|g"
          "s|cros_efi|cros_efi systemd.mask=sshd.service|g"
          "s|cros_efi|cros_efi systemd.mask=var-lib-toolbox.mount|g"
          "s|cros_efi|cros_efi systemd.mask=update-engine.service|g"
          "s|cros_efi|cros_efi confidential-space.hardened=true|g"
        )

        CMD=(
          "/oem-preloader"
          "--vmlinux=./vmlinux"
          "--src-image=./disk.raw"
          "--out-image=output.bin"
          "--oem-fs-size=500M"
          "--disk-size-gb=16"
          "--install-dir=/workspace/oem-install/"
        )
        for cmd in "$${COMMON_COMMANDS[@]}"; do
          CMD+=(--cmdline-sed-command="$${cmd}")
        done
        if [[ "$${IMAGE_ENV}" == "debug" ]]; then
          for cmd in "$${DEBUG_COMMANDS[@]}"; do
            CMD+=(--cmdline-sed-command="$${cmd}")
          done
        elif [[ "$${IMAGE_ENV}" == "hardened" ]]; then
          for cmd in "$${HARDENED_COMMANDS[@]}"; do
            CMD+=(--cmdline-sed-command="$${cmd}")
          done
        fi

        "$${CMD[@]}"
  - name: 'alpine'
    id: 'RenameOutputImage'
    args: ['mv', 'output.bin', 'disk.raw']
  - name: 'alpine'
    id: 'TarOutputImage'
    args: ['tar', '-zcf', './out_image.tar.gz', 'disk.raw']
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'UploadToGCS'
    entrypoint: 'gcloud'
    args: ['storage',
           'cp',
           './out_image.tar.gz',
           'gs://${_BUCKET_NAME}/oem-preloader-${BUILD_ID}/${_OUTPUT_IMAGE_NAME}.tar.gz']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'FetchBaseImageFeatures'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud compute images describe ${_BASE_IMAGE} --project=${_BASE_IMAGE_PROJECT} --format="value(guestOsFeatures.type)" | paste -sd, - | tr ';' ',' | tr -d '\n' > /workspace/features.txt
        sed -i 's/SECURE_BOOT//g' /workspace/features.txt
        sed -i 's/,,/,/g' /workspace/features.txt
        sed -i 's/^,//; s/,$//' /workspace/features.txt
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'CreateGCEImage'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        FEATURES=$$(cat /workspace/features.txt)
        if [ -z "$$FEATURES" ]; then
          FEATURES="UEFI_COMPATIBLE"
        fi
        gcloud compute images create ${_OUTPUT_IMAGE_NAME} \
          --family=${_OUTPUT_IMAGE_FAMILY} \
          --source-uri=gs://${_BUCKET_NAME}/oem-preloader-${BUILD_ID}/${_OUTPUT_IMAGE_NAME}.tar.gz \
          --guest-os-features="$$FEATURES" \
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'RemoveGCSFiles'
    entrypoint: 'gcloud'
    args: ['storage',
           'rm',
           'gs://${_BUCKET_NAME}/oem-preloader-${BUILD_ID}/${_BASE_IMAGE}.tar.gz',
           'gs://${_BUCKET_NAME}/oem-preloader-${BUILD_ID}/${_OUTPUT_IMAGE_NAME}.tar.gz']

timeout: '3000s'

options:
  machine_type: 'E2_HIGHCPU_32'
  dynamic_substitutions: true