package workloadservice

import (
	"fmt"
	"strings"

	keymanager "github.com/google/go-tpm-tools/keymanager/km_common/proto"
	api "github.com/google/go-tpm-tools/keymanager/workload_service/proto"
)

// Supported algorithms and mechanisms.
var (
	// SupportedKemAlgorithms is the source of truth for supported algorithms.
	SupportedKemAlgorithms = []api.KemAlgorithm{
		api.KemAlgorithm_DHKEM_X25519_HKDF_SHA256,
	}
)

// IsSupportedKemAlgorithm returns true if the KEM algorithm is supported.
func IsSupportedKemAlgorithm(k api.KemAlgorithm) bool {
	for _, supported := range SupportedKemAlgorithms {
		if k == supported {
			return true
		}
	}
	return false
}

// SupportedKemAlgorithmsString returns a comma-separated list of supported KEM algorithms.
func SupportedKemAlgorithmsString() string {
	var names []string
	for _, k := range SupportedKemAlgorithms {
		names = append(names, k.String()) // api.KemAlgorithm has a String() method generated by proto
	}
	return strings.Join(names, ", ")
}

// KemToHpkeAlgorithm returns the full HPKE suite configuration for this algorithm.
func KemToHpkeAlgorithm(k api.KemAlgorithm) (*keymanager.HpkeAlgorithm, error) {
	switch k {
	case api.KemAlgorithm_DHKEM_X25519_HKDF_SHA256:
		return &keymanager.HpkeAlgorithm{
			Kem:  keymanager.KemAlgorithm_KEM_ALGORITHM_DHKEM_X25519_HKDF_SHA256,
			Kdf:  keymanager.KdfAlgorithm_KDF_ALGORITHM_HKDF_SHA256,
			Aead: keymanager.AeadAlgorithm_AEAD_ALGORITHM_AES_256_GCM,
		}, nil
	default:
		return nil, fmt.Errorf("unsupported algorithm: %s", k)
	}
}

// MapKemToAPI converts keymanager.KemAlgorithm to api.KemAlgorithm
func MapKemToAPI(k keymanager.KemAlgorithm) api.KemAlgorithm {
	switch k {
	case keymanager.KemAlgorithm_KEM_ALGORITHM_DHKEM_X25519_HKDF_SHA256:
		return api.KemAlgorithm_DHKEM_X25519_HKDF_SHA256
	default:
		return api.KemAlgorithm_KEM_ALGORITHM_UNSPECIFIED
	}
}
