// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.4
// source: bmsai/agent.proto

package bmsai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BmsaiAttestationService_MeasureEvent_FullMethodName = "/google.tpmtools.bmsai.BmsaiAttestationService/MeasureEvent"
	BmsaiAttestationService_GetEvidence_FullMethodName  = "/google.tpmtools.bmsai.BmsaiAttestationService/GetEvidence"
)

// BmsaiAttestationServiceClient is the client API for BmsaiAttestationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BmsaiAttestationService coordinates bare-metal attestation operations on GB300.
type BmsaiAttestationServiceClient interface {
	// MeasureEvent appends a canonical COS event (GPU SPDM report, container claim,
	// or launch separator) to cel_launch_event_log and extends its SHA-384 digest into
	// TEM 1 (go-bmsai slot 2) and its SHA-256 digest into Dauntless dTPM PCR 19.
	MeasureEvent(ctx context.Context, in *MeasureEventRequest, opts ...grpc.CallOption) (*MeasureEventResponse, error)
	// GetEvidence returns BmsaiEvidence + confidential_space.TpmQuote bound to supplied challenge nonce.
	GetEvidence(ctx context.Context, in *GetEvidenceRequest, opts ...grpc.CallOption) (*Gb300Evidence, error)
}

type bmsaiAttestationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBmsaiAttestationServiceClient(cc grpc.ClientConnInterface) BmsaiAttestationServiceClient {
	return &bmsaiAttestationServiceClient{cc}
}

func (c *bmsaiAttestationServiceClient) MeasureEvent(ctx context.Context, in *MeasureEventRequest, opts ...grpc.CallOption) (*MeasureEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeasureEventResponse)
	err := c.cc.Invoke(ctx, BmsaiAttestationService_MeasureEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bmsaiAttestationServiceClient) GetEvidence(ctx context.Context, in *GetEvidenceRequest, opts ...grpc.CallOption) (*Gb300Evidence, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Gb300Evidence)
	err := c.cc.Invoke(ctx, BmsaiAttestationService_GetEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BmsaiAttestationServiceServer is the server API for BmsaiAttestationService service.
// All implementations must embed UnimplementedBmsaiAttestationServiceServer
// for forward compatibility.
//
// BmsaiAttestationService coordinates bare-metal attestation operations on GB300.
type BmsaiAttestationServiceServer interface {
	// MeasureEvent appends a canonical COS event (GPU SPDM report, container claim,
	// or launch separator) to cel_launch_event_log and extends its SHA-384 digest into
	// TEM 1 (go-bmsai slot 2) and its SHA-256 digest into Dauntless dTPM PCR 19.
	MeasureEvent(context.Context, *MeasureEventRequest) (*MeasureEventResponse, error)
	// GetEvidence returns BmsaiEvidence + confidential_space.TpmQuote bound to supplied challenge nonce.
	GetEvidence(context.Context, *GetEvidenceRequest) (*Gb300Evidence, error)
	mustEmbedUnimplementedBmsaiAttestationServiceServer()
}

// UnimplementedBmsaiAttestationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBmsaiAttestationServiceServer struct{}

func (UnimplementedBmsaiAttestationServiceServer) MeasureEvent(context.Context, *MeasureEventRequest) (*MeasureEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MeasureEvent not implemented")
}
func (UnimplementedBmsaiAttestationServiceServer) GetEvidence(context.Context, *GetEvidenceRequest) (*Gb300Evidence, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvidence not implemented")
}
func (UnimplementedBmsaiAttestationServiceServer) mustEmbedUnimplementedBmsaiAttestationServiceServer() {
}
func (UnimplementedBmsaiAttestationServiceServer) testEmbeddedByValue() {}

// UnsafeBmsaiAttestationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BmsaiAttestationServiceServer will
// result in compilation errors.
type UnsafeBmsaiAttestationServiceServer interface {
	mustEmbedUnimplementedBmsaiAttestationServiceServer()
}

func RegisterBmsaiAttestationServiceServer(s grpc.ServiceRegistrar, srv BmsaiAttestationServiceServer) {
	// If the following call pancis, it indicates UnimplementedBmsaiAttestationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BmsaiAttestationService_ServiceDesc, srv)
}

func _BmsaiAttestationService_MeasureEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeasureEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BmsaiAttestationServiceServer).MeasureEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BmsaiAttestationService_MeasureEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BmsaiAttestationServiceServer).MeasureEvent(ctx, req.(*MeasureEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BmsaiAttestationService_GetEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEvidenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BmsaiAttestationServiceServer).GetEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BmsaiAttestationService_GetEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BmsaiAttestationServiceServer).GetEvidence(ctx, req.(*GetEvidenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BmsaiAttestationService_ServiceDesc is the grpc.ServiceDesc for BmsaiAttestationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BmsaiAttestationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "google.tpmtools.bmsai.BmsaiAttestationService",
	HandlerType: (*BmsaiAttestationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MeasureEvent",
			Handler:    _BmsaiAttestationService_MeasureEvent_Handler,
		},
		{
			MethodName: "GetEvidence",
			Handler:    _BmsaiAttestationService_GetEvidence_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
