// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.23.4
// source: bmsai/agent.proto

package bmsai

import (
	attestation "github.com/GoogleCloudPlatform/confidential-space/server/proto/gen/attestation"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MeasureEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Binary CEL TLV of type 80 (COS event) whose value is a nested cel.CosTlv
	// (Event Type + Content). Any other TLV type is rejected with INVALID_ARGUMENT.
	// The extended digests are computed over exactly these bytes.
	CosEvent      []byte `protobuf:"bytes,1,opt,name=cos_event,json=cosEvent,proto3" json:"cos_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasureEventRequest) Reset() {
	*x = MeasureEventRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasureEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasureEventRequest) ProtoMessage() {}

func (x *MeasureEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasureEventRequest.ProtoReflect.Descriptor instead.
func (*MeasureEventRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *MeasureEventRequest) GetCosEvent() []byte {
	if x != nil {
		return x.CosEvent
	}
	return nil
}

type MeasureEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success indicator. Any extension failure returns a gRPC status error.
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasureEventResponse) Reset() {
	*x = MeasureEventResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasureEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasureEventResponse) ProtoMessage() {}

func (x *MeasureEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasureEventResponse.ProtoReflect.Descriptor instead.
func (*MeasureEventResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *MeasureEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetEvidenceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Verifier or workload challenge nonce (8..64 bytes).
	Challenge     []byte `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEvidenceRequest) Reset() {
	*x = GetEvidenceRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEvidenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEvidenceRequest) ProtoMessage() {}

func (x *GetEvidenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEvidenceRequest.ProtoReflect.Descriptor instead.
func (*GetEvidenceRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *GetEvidenceRequest) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

// Top-level evidence message returned to teeserver and workload container.
type Gb300Evidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BmsaiEvidence *BmsaiEvidence         `protobuf:"bytes,1,opt,name=bmsai_evidence,json=bmsaiEvidence,proto3" json:"bmsai_evidence,omitempty"`
	TpmQuote      *attestation.TpmQuote  `protobuf:"bytes,2,opt,name=tpm_quote,json=tpmQuote,proto3" json:"tpm_quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gb300Evidence) Reset() {
	*x = Gb300Evidence{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gb300Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gb300Evidence) ProtoMessage() {}

func (x *Gb300Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gb300Evidence.ProtoReflect.Descriptor instead.
func (*Gb300Evidence) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Gb300Evidence) GetBmsaiEvidence() *BmsaiEvidence {
	if x != nil {
		return x.BmsaiEvidence
	}
	return nil
}

func (x *Gb300Evidence) GetTpmQuote() *attestation.TpmQuote {
	if x != nil {
		return x.TpmQuote
	}
	return nil
}

type BmsaiEvidence struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw CBOR-encoded Tag 907 Conceptual Measurement Wrapper (CMW) bundle
	// containing Platform Lane (Claim 44234) and Tenant Lane (Claim 44241).
	BmCmwToken []byte `protobuf:"bytes,1,opt,name=bm_cmw_token,json=bmCmwToken,proto3" json:"bm_cmw_token,omitempty"`
	// DRTM / DLME Boot Event Log (/sys/kernel/security/slaunch/drtm_event_log)
	// Binary TCG_PCR_EVENT2 records extended into TEM Slot 0 (Claim 44238).
	DrtmBootEventLog []byte `protobuf:"bytes,2,opt,name=drtm_boot_event_log,json=drtmBootEventLog,proto3" json:"drtm_boot_event_log,omitempty"`
	// Canonical Event Log (/run/container_launcher/bmsai_event_log)
	// Binary cel.CosTlv records whose SHA-384 digests are extended into TEM 1
	// (go-bmsai slot 2); the same events' SHA-256 digests are extended
	// into dTPM PCR 19 (TpmQuote.cel_launch_event_log).
	CelLaunchEventLog []byte `protobuf:"bytes,3,opt,name=cel_launch_event_log,json=celLaunchEventLog,proto3" json:"cel_launch_event_log,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BmsaiEvidence) Reset() {
	*x = BmsaiEvidence{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BmsaiEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BmsaiEvidence) ProtoMessage() {}

func (x *BmsaiEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BmsaiEvidence.ProtoReflect.Descriptor instead.
func (*BmsaiEvidence) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *BmsaiEvidence) GetBmCmwToken() []byte {
	if x != nil {
		return x.BmCmwToken
	}
	return nil
}

func (x *BmsaiEvidence) GetDrtmBootEventLog() []byte {
	if x != nil {
		return x.DrtmBootEventLog
	}
	return nil
}

func (x *BmsaiEvidence) GetCelLaunchEventLog() []byte {
	if x != nil {
		return x.CelLaunchEventLog
	}
	return nil
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x15google.tpmtools.bmsai\x1a\x11attestation.proto\"2\n" +
	"\x13MeasureEventRequest\x12\x1b\n" +
	"\tcos_event\x18\x01 \x01(\fR\bcosEvent\"0\n" +
	"\x14MeasureEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x12GetEvidenceRequest\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\fR\tchallenge\"\x97\x01\n" +
	"\rGb300Evidence\x12K\n" +
	"\x0ebmsai_evidence\x18\x01 \x01(\v2$.google.tpmtools.bmsai.BmsaiEvidenceR\rbmsaiEvidence\x129\n" +
	"\ttpm_quote\x18\x02 \x01(\v2\x1c.confidential_space.TpmQuoteR\btpmQuote\"\x91\x01\n" +
	"\rBmsaiEvidence\x12 \n" +
	"\fbm_cmw_token\x18\x01 \x01(\fR\n" +
	"bmCmwToken\x12-\n" +
	"\x13drtm_boot_event_log\x18\x02 \x01(\fR\x10drtmBootEventLog\x12/\n" +
	"\x14cel_launch_event_log\x18\x03 \x01(\fR\x11celLaunchEventLog2\xe2\x01\n" +
	"\x17BmsaiAttestationService\x12g\n" +
	"\fMeasureEvent\x12*.google.tpmtools.bmsai.MeasureEventRequest\x1a+.google.tpmtools.bmsai.MeasureEventResponse\x12^\n" +
	"\vGetEvidence\x12).google.tpmtools.bmsai.GetEvidenceRequest\x1a$.google.tpmtools.bmsai.Gb300EvidenceB,Z*github.com/google/go-tpm-tools/proto/bmsaib\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_agent_proto_goTypes = []any{
	(*MeasureEventRequest)(nil),  // 0: google.tpmtools.bmsai.MeasureEventRequest
	(*MeasureEventResponse)(nil), // 1: google.tpmtools.bmsai.MeasureEventResponse
	(*GetEvidenceRequest)(nil),   // 2: google.tpmtools.bmsai.GetEvidenceRequest
	(*Gb300Evidence)(nil),        // 3: google.tpmtools.bmsai.Gb300Evidence
	(*BmsaiEvidence)(nil),        // 4: google.tpmtools.bmsai.BmsaiEvidence
	(*attestation.TpmQuote)(nil), // 5: confidential_space.TpmQuote
}
var file_agent_proto_depIdxs = []int32{
	4, // 0: google.tpmtools.bmsai.Gb300Evidence.bmsai_evidence:type_name -> google.tpmtools.bmsai.BmsaiEvidence
	5, // 1: google.tpmtools.bmsai.Gb300Evidence.tpm_quote:type_name -> confidential_space.TpmQuote
	0, // 2: google.tpmtools.bmsai.BmsaiAttestationService.MeasureEvent:input_type -> google.tpmtools.bmsai.MeasureEventRequest
	2, // 3: google.tpmtools.bmsai.BmsaiAttestationService.GetEvidence:input_type -> google.tpmtools.bmsai.GetEvidenceRequest
	1, // 4: google.tpmtools.bmsai.BmsaiAttestationService.MeasureEvent:output_type -> google.tpmtools.bmsai.MeasureEventResponse
	3, // 5: google.tpmtools.bmsai.BmsaiAttestationService.GetEvidence:output_type -> google.tpmtools.bmsai.Gb300Evidence
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
